"use client";
import React, { useMemo, useState } from "react";
import { useApp } from "@/stores/app-store";
import { trainingActions } from "@/stores/actions";
import { AREAS, AreaId } from "@/types/app-data";
import { trainingStats, trainingSessionXp } from "@/calculations/training";
import { formatShort, todayISO, WEEKDAY_SHORT_AR } from "@/core/date";
import { Button, Card, Chip, EmptyState, Field, Grid, Input, Modal, NumberInput, ProgressBar, StatCard, useConfirm } from "@/components/ui";
import { BarSeries } from "@/components/charts";

export default function TrainingPage() {
  const data = useApp((s) => s.data); const log = data.trainingLog; const st = useMemo(() => trainingStats(log), [log]); const { confirm, dialog } = useConfirm();
  const [f, setF] = useState({ areaId: log.areas[0]?.id ?? "", minutes: 45, note: "", date: todayISO() }); const [areaOpen, setAreaOpen] = useState(false); const [na, setNa] = useState({ name: "", color: "#8b5cf6", lifeArea: "career" as AreaId });
  return (<div className="space-y-4 anim-fade-up">
    <Grid cols={4}><StatCard label="هذا الأسبوع" value={`${st.weekMinutes} د`} hint={`${st.weekSessions} جلسة`} tone="accent" icon="📅" /><StatCard label="هذا الشهر" value={`${st.monthMinutes} د`} hint={`${st.monthSessions} جلسة`} icon="🗓️" /><StatCard label="إجمالي" value={`${Math.round(st.lifetimeMinutes / 60)} س`} hint={`${st.lifetimeSessions} جلسة`} tone="gold" icon="🏆" /><StatCard label="السلسلة" value={`${st.currentStreak} يوم`} hint={`الأفضل ${st.bestStreak}`} icon="🔥" /></Grid>
    <Card title="تسجيل جلسة تدريب" subtitle={`XP = دقائق/10 (3–30) · هذه الجلسة: +${trainingSessionXp(f.minutes)}`}><div className="space-y-3"><div className="flex flex-wrap gap-1.5">{log.areas.map((a) => <Chip key={a.id} active={f.areaId === a.id} color={a.color} onClick={() => setF({ ...f, areaId: a.id })}>{a.name}</Chip>)}<Chip onClick={() => setAreaOpen(true)}>+ مجال</Chip></div><div className="grid gap-2 sm:grid-cols-4"><NumberInput value={f.minutes} step={5} suffix="د" onChange={(v) => setF({ ...f, minutes: v })} /><Input type="date" value={f.date} onChange={(e) => setF({ ...f, date: e.target.value })} /><Input placeholder="ملاحظة" value={f.note} onChange={(e) => setF({ ...f, note: e.target.value })} /><Button variant="primary" disabled={!f.areaId || f.minutes <= 0} onClick={() => { trainingActions.addSession(f); setF({ ...f, note: "" }); }}>تسجيل</Button></div></div></Card>
    <Grid><BarSeries title="آخر 8 أسابيع" data={st.last8Weeks.map((w) => ({ w: w.label, m: w.minutes }))} x="w" series={[{ key: "m", color: "var(--accent)", name: "دقائق" }]} height={200} /><BarSeries title="توزيع أيام الأسبوع" data={st.weekdayDist.map((d) => ({ d: WEEKDAY_SHORT_AR[d.day], m: d.minutes }))} x="d" series={[{ key: "m", color: "var(--gold)", name: "دقائق" }]} height={200} /></Grid>
    <Grid cols={3}><StatCard label="أفضل يوم" value={st.bestDay ? `${st.bestDay.minutes} د` : "—"} hint={st.bestDay ? formatShort(st.bestDay.date) : ""} /><StatCard label="أفضل أسبوع" value={st.bestWeek ? `${st.bestWeek.minutes} د` : "—"} hint={st.bestWeek ? `أسبوع ${formatShort(st.bestWeek.week)}` : ""} /><StatCard label="أطول سلسلة" value={`${st.bestStreak} يوم`} /></Grid>
    <Card title="توزيع المجالات">{st.areaBreakdown.map((a) => <div key={a.areaId} className="mb-2"><div className="flex justify-between text-xs"><span><span className="inline-block h-2 w-2 rounded-full" style={{ background: a.color }} /> {a.name} · {AREAS.find((x) => x.id === log.areas.find((y) => y.id === a.areaId)?.lifeArea)?.label}</span><span>{a.minutes} د · {a.sessions} جلسة · {a.percent}%</span></div><ProgressBar value={a.percent} color={a.color} label={a.name} /></div>)}{!st.areaBreakdown.length && <EmptyState icon="🧭" title="لا مجالات" />}</Card>
    <Card title="آخر الجلسات"><div className="max-h-72 space-y-1 overflow-y-auto text-sm">{[...log.sessions].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 50).map((s) => { const a = log.areas.find((x) => x.id === s.areaId); return <div key={s.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-2"><span><span className="inline-block h-2 w-2 rounded-full" style={{ background: a?.color }} /> {a?.name ?? "—"} · {s.minutes} د <span className="text-xs text-muted">{s.date} {s.note}</span></span><span className="flex items-center gap-2 text-xs text-gold">+{s.xp}<button type="button" aria-label="حذف" onClick={() => confirm("حذف الجلسة؟", () => trainingActions.removeSession(s.id))}>🗑</button></span></div>; })}{!log.sessions.length && <EmptyState icon="⏱️" title="لا جلسات بعد" />}</div></Card>
    <Modal open={areaOpen} onClose={() => setAreaOpen(false)} title="مجال تدريب جديد" size="sm" footer={<Button variant="primary" disabled={!na.name} onClick={() => { trainingActions.addArea(na.name, na.color, na.lifeArea); setAreaOpen(false); setNa({ ...na, name: "" }); }}>إضافة</Button>}><div className="space-y-3"><Field label="الاسم"><Input value={na.name} onChange={(e) => setNa({ ...na, name: e.target.value })} /></Field><Field label="اللون"><input type="color" value={na.color} onChange={(e) => setNa({ ...na, color: e.target.value })} className="h-11 w-full rounded-xl" aria-label="اللون" /></Field><Field label="محور الحياة"><div className="flex flex-wrap gap-1.5">{AREAS.map((a) => <Chip key={a.id} active={na.lifeArea === a.id} color={a.color} onClick={() => setNa({ ...na, lifeArea: a.id })}>{a.emoji} {a.label}</Chip>)}</div></Field><div className="text-xs text-muted">المجالات المخصصة: {log.areas.filter((a) => a.custom).map((a) => <button key={a.id} type="button" className="me-1 underline" onClick={() => trainingActions.removeArea(a.id)}>{a.name} ✕</button>)}</div></div></Modal>{dialog}
  </div>);
}
