"use client";
import React, { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useApp } from "@/stores/app-store";
import { recoveryActions } from "@/stores/actions";
import { LostThing } from "@/types/app-data";
import { addictionIndex, checkInsForDay, computeRisk, PHASES, RECOVERY_DISCLAIMER, recoveryAnalytics, recoveryIndex, recoveryPhase, relapseGaps, sobrietyStats, SOBRIETY_MILESTONES } from "@/calculations/recovery";
import { formatShort, todayISO, WEEKDAY_SHORT_AR, weekday } from "@/core/date";
import { Button, Card, Chip, Disclaimer, EmptyState, Field, Grid, Input, Modal, ProgressBar, ProgressRing, Select, Slider, StatCard, Tabs, Textarea, cx, useConfirm } from "@/components/ui";
import { LineSeries, BarSeries } from "@/components/charts";

function useNow(ms = 1000) { const [n, setN] = useState(() => new Date()); useEffect(() => { const t = setInterval(() => setN(new Date()), ms); return () => clearInterval(t); }, [ms]); return n; }
const fmtDur = (ms: number) => { const s = Math.floor(ms / 1000); const d = Math.floor(s / 86400), h = Math.floor((s % 86400) / 3600), m = Math.floor((s % 3600) / 60), sec = s % 60; return `${d}ي ${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")}`; };

export default function HealingPage() {
  const data = useApp((s) => s.data); const sp = useSearchParams(); const [tab, setTab] = useState<"today" | "sos" | "relapse" | "tasks" | "lost" | "analytics" | "phase">(sp?.get("sos") ? "sos" : "today");
  const now = useNow(); const stats = useMemo(() => sobrietyStats(data, now), [data, now]); const risk = useMemo(() => computeRisk(data), [data]); const idx = useMemo(() => recoveryIndex(data), [data]); const phase = recoveryPhase(stats.currentDays);
  const [startOpen, setStartOpen] = useState(false); const [startVal, setStartVal] = useState(todayISO());
  const riskColor = { low: "var(--ok)", moderate: "var(--warn)", high: "#f97316", critical: "var(--danger)" }[risk.level];
  return (<div className="space-y-4 anim-fade-up">
    <Card className="relative overflow-hidden"><div className="pointer-events-none absolute -start-10 -top-10 h-40 w-40 rounded-full bg-ok/10 blur-3xl" aria-hidden />
      {!stats.startAt ? <div className="text-center"><div className="text-3xl">🌱</div><h2 className="mt-1 text-lg font-black">رحلة التعافي</h2><p className="text-sm text-muted">حدد بداية رحلتك لتفعيل العدّاد والمؤشرات والمراحل.</p><Button variant="primary" className="mt-3" onClick={() => setStartOpen(true)}>تحديد البداية</Button></div>
        : <div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><div><div className="text-xs text-muted">نظيف منذ</div><div className="font-mono text-2xl font-black tabular-nums md:text-3xl">{fmtDur(stats.currentMs)}</div><div className="mt-1 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-surface-2 px-2 py-0.5">اليوم {stats.currentDays + 1}</span><span className="rounded-full bg-surface-2 px-2 py-0.5">أطول سلسلة: {stats.longestDays} يوم</span><span className="rounded-full bg-gold-soft px-2 py-0.5 text-gold">المرحلة: {phase.label}</span>{stats.nextMilestone && <span className="rounded-full bg-surface-2 px-2 py-0.5">المعلم القادم: {stats.nextMilestone} يوم (باقي {stats.nextMilestone - stats.currentDays})</span>}</div><div className="mt-2 flex gap-1">{SOBRIETY_MILESTONES.slice(0, 10).map((m) => <span key={m} title={`${m} يوم`} className={cx("h-2 flex-1 rounded-full", stats.currentDays >= m ? "bg-gold" : "bg-surface-2")} />)}</div><button type="button" className="mt-2 text-[11px] text-muted underline" onClick={() => setStartOpen(true)}>تعديل تاريخ البداية</button></div>
          <div className="flex flex-col items-center"><ProgressRing value={idx.value} size={84} color="var(--ok)" label="مؤشر التعافي" /><span className="text-[11px] text-muted">مؤشر التعافي</span></div>
          {data.recoveryCoachSettings.showRisk && <div className="flex flex-col items-center"><ProgressRing value={risk.score} size={84} color={riskColor} label="مؤشر الخطر"><span className="text-sm font-black" style={{ color: riskColor }}>{risk.label}</span></ProgressRing><span className="text-[11px] text-muted">الخطر الآن {risk.score}</span></div>}</div>}
    </Card>
    <Button block size="lg" variant="danger" onClick={() => setTab("sos")} className="border border-danger/40 text-base">🆘 SOS — أحتاج مساعدة الآن</Button>
    <Tabs value={tab} onChange={setTab} tabs={[{ id: "today", label: "اليوم" }, { id: "sos", label: "SOS" }, { id: "relapse", label: "الانتكاسات" }, { id: "tasks", label: "المهام" }, { id: "lost", label: "ما فقدته" }, { id: "analytics", label: "التحليلات" }, { id: "phase", label: "المرحلة" }]} />
    {tab === "today" && <TodayTab risk={risk} idx={idx} />}
    {tab === "sos" && <SosTab />}
    {tab === "relapse" && <RelapseTab />}
    {tab === "tasks" && <TasksTab />}
    {tab === "lost" && <LostTab />}
    {tab === "analytics" && <AnalyticsTab />}
    {tab === "phase" && <PhaseTab days={stats.currentDays} />}
    <Modal open={startOpen} onClose={() => setStartOpen(false)} title="بداية الرحلة" size="sm" footer={<Button variant="primary" onClick={() => { recoveryActions.setSobrietyStart(new Date(startVal).toISOString()); setStartOpen(false); }}>حفظ</Button>}><Field label="التاريخ"><Input type="date" value={startVal} onChange={(e) => setStartVal(e.target.value)} /></Field></Modal>
  </div>);
}

function TodayTab({ risk, idx }: { risk: ReturnType<typeof computeRisk>; idx: ReturnType<typeof recoveryIndex> }) {
  const data = useApp((s) => s.data); const today = todayISO(); const readings = checkInsForDay(data, today);
  const [f, setF] = useState({ mood: 6, spiritual: 6, urge: 2, note: "", timing: (new Date().getHours() < 14 ? "morning" : "evening") as "morning" | "evening" | "other", ritualsDone: [] as string[] });
  const morning = data.morningReviews.find((r) => r.periodKey === today); const [ma, setMa] = useState<Record<string, string>>(morning?.answers ?? {});
  return (<div className="space-y-3">
    <Card title="قراءة الآن" subtitle={`${readings.length} قراءة اليوم · يمكن تسجيل أكثر من قراءة`}><div className="grid gap-3 sm:grid-cols-3"><Slider label="المزاج" value={f.mood} min={1} max={10} onChange={(v) => setF({ ...f, mood: v })} marks={["سيئ", "ممتاز"]} /><Slider label="الحالة الروحية" value={f.spiritual} min={1} max={10} onChange={(v) => setF({ ...f, spiritual: v })} marks={["بعيد", "قريب"]} /><Slider label="الرغبة" value={f.urge} min={0} max={10} onChange={(v) => setF({ ...f, urge: v })} marks={["لا شيء", "قصوى"]} /></div>
      <div className="mt-3 grid gap-2 sm:grid-cols-[auto_1fr]"><Select value={f.timing} onChange={(e) => setF({ ...f, timing: e.target.value as "morning" })}><option value="morning">صباح</option><option value="evening">مساء</option><option value="other">أخرى</option></Select><Input placeholder="ملاحظة قصيرة" value={f.note} onChange={(e) => setF({ ...f, note: e.target.value })} /></div>
      {data.recoveryRituals.length > 0 && <div className="mt-2"><div className="mb-1 text-xs font-bold text-muted">الطقوس المنفذة</div><div className="flex flex-wrap gap-1.5">{data.recoveryRituals.map((r) => <Chip key={r.id} active={f.ritualsDone.includes(r.id)} onClick={() => setF({ ...f, ritualsDone: f.ritualsDone.includes(r.id) ? f.ritualsDone.filter((x) => x !== r.id) : [...f.ritualsDone, r.id] })}>{r.name}</Chip>)}</div></div>}
      <Button variant="primary" className="mt-3" onClick={() => { recoveryActions.checkIn(f); setF({ ...f, note: "", ritualsDone: [] }); }}>تسجيل القراءة (+XP)</Button>
      {readings.length > 0 && <ul className="mt-3 space-y-1 text-xs">{readings.map((r) => <li key={r.id} className="flex justify-between rounded-lg bg-surface-2 px-2 py-1"><span>{r.at.slice(11, 16)} · {r.timing === "morning" ? "صباح" : r.timing === "evening" ? "مساء" : "—"}</span><span>مزاج {r.mood} · روح {r.spiritual} · رغبة {r.urge}</span></li>)}</ul>}</Card>
    <Grid><Card title={`مؤشر الخطر: ${risk.label} (${risk.score})`} tone={risk.level === "critical" || risk.level === "high" ? "danger" : undefined}><div className="space-y-1 text-xs">{risk.factors.map((x) => <div key={x.label} className="flex justify-between"><span>▲ {x.label}</span><b className="text-danger">+{x.weight}</b></div>)}{risk.protections.map((x) => <div key={x.label} className="flex justify-between"><span>▼ {x.label}</span><b className="text-ok">−{x.weight}</b></div>)}</div><div className="mt-2 text-xs font-bold">خطة اليوم:</div><ul className="list-inside list-disc text-xs text-muted">{risk.plan.map((p) => <li key={p}>{p}</li>)}</ul></Card>
      <Card title={`مؤشر التعافي ${idx.value}/100`}>{idx.parts.map((p) => <div key={p.label} className="mb-2"><div className="flex justify-between text-xs"><span>{p.label}</span><span>{p.value}/{p.max}</span></div><ProgressBar value={(p.value / p.max) * 100} color="var(--ok)" label={p.label} /></div>)}<div className="text-xs text-muted">مؤشر الإدمان (30 يوم): <b>{addictionIndex(data)}</b>/100</div></Card></Grid>
    <Card title="مراجعة الصباح" subtitle={morning ? "محفوظة" : "+8 XP"}><div className="space-y-2">{data.morningRecoveryQuestions.map((q) => <Field key={q.id} label={q.text}><Input value={ma[q.id] ?? ""} onChange={(e) => setMa({ ...ma, [q.id]: e.target.value })} /></Field>)}<Button onClick={() => recoveryActions.saveMorning(today, ma)}>حفظ</Button></div></Card>
    <Disclaimer>{RECOVERY_DISCLAIMER}</Disclaimer>
  </div>);
}

function SosTab() {
  const data = useApp((s) => s.data); const [breath, setBreath] = useState(false); const [phase, setPhase] = useState("استعد"); const [count, setCount] = useState(0);
  const [cr, setCr] = useState({ urge: 7, triggers: [] as string[], note: "" }); const [done, setDone] = useState<string | null>(null);
  useEffect(() => { if (!breath) return; const cycle = [["شهيق", 4], ["احبس", 7], ["زفير", 8]] as const; let i = 0, t = 0; setPhase(cycle[0][0]); setCount(cycle[0][1]); const id = setInterval(() => { t++; if (t >= cycle[i][1]) { t = 0; i = (i + 1) % 3; setPhase(cycle[i][0]); } setCount(cycle[i][1] - t); }, 1000); return () => clearInterval(id); }, [breath]);
  const log = (outcome: "resisted" | "relapse") => { const ev = recoveryActions.craving({ ...cr, triggers: cr.triggers.map((id) => data.recoveryTriggers.find((t) => t.id === id)?.name ?? id), outcome }); setDone(outcome === "resisted" ? `سجلت مقاومة — +${ev.xp} XP. الموجة تمر. أنت أقوى مما كنت قبل دقيقة.` : "سُجل. الصدق نصف التعافي. سجّل الانتكاس بالتفصيل في تبويب الانتكاسات ثم ارجع فورًا."); };
  return (<div className="space-y-3">
    <Card title="١ · تنفّس 4-7-8" tone="accent"><div className="grid place-items-center gap-2 py-3"><div className="grid h-36 w-36 place-items-center rounded-full bg-accent-soft" style={breath ? { animation: "breathe 19s ease-in-out infinite" } : undefined}><div className="text-center"><div className="text-xl font-black">{phase}</div><div className="text-3xl font-black tabular-nums">{breath ? count : ""}</div></div></div><Button variant={breath ? "soft" : "primary"} onClick={() => setBreath(!breath)}>{breath ? "إيقاف" : "ابدأ التنفس"}</Button></div></Card>
    <Card title="٢ · غيّر بيئتك"><p className="text-sm">قم الآن. اخرج من الغرفة. ضع الجوال في غرفة أخرى. توضأ. الموجة تبلغ ذروتها خلال 15–20 دقيقة ثم تهبط — مهما كانت شدتها.</p></Card>
    <Card title="٣ · بروتوكول الإنقاذ"><ol className="list-inside list-decimal space-y-1 text-sm">{data.rescueProtocol.steps.map((s, i) => <li key={i}>{s}</li>)}</ol>{data.rescueProtocol.supportContact ? <a href={`tel:${data.rescueProtocol.supportContact}`} className="mt-3 inline-flex min-h-[44px] items-center rounded-xl bg-ok px-4 font-bold text-white">📞 اتصل بشخص الدعم</a> : <p className="mt-2 text-xs text-muted">أضف رقم شخص الدعم من الإعدادات › بروتوكول الإنقاذ.</p>}</Card>
    {data.recoveryReasons.length > 0 && <Card title="٤ · أسبابك"><ul className="space-y-1 text-sm">{data.recoveryReasons.map((r) => <li key={r.id} className="rounded-xl bg-gold-soft px-3 py-2">✦ {r.text}</li>)}</ul></Card>}
    {data.recoveryLetter.text && <Card title="٥ · رسالتك لنفسك" tone="gold"><p className="whitespace-pre-wrap text-sm leading-7">{data.recoveryLetter.text}</p></Card>}
    <Card title="٦ · سجّل الرغبة" subtitle="التسجيل نفسه يقلل الشدة">{done ? <div className="rounded-xl bg-ok/10 p-3 text-sm">{done}<Button size="sm" className="mt-2" onClick={() => setDone(null)}>تسجيل أخرى</Button></div> : <div className="space-y-3"><Slider label="شدة الرغبة" value={cr.urge} min={0} max={10} onChange={(v) => setCr({ ...cr, urge: v })} /><div><div className="mb-1 text-xs font-bold text-muted">المحفزات</div><div className="flex flex-wrap gap-1.5">{data.recoveryTriggers.map((t) => <Chip key={t.id} active={cr.triggers.includes(t.id)} onClick={() => setCr({ ...cr, triggers: cr.triggers.includes(t.id) ? cr.triggers.filter((x) => x !== t.id) : [...cr.triggers, t.id] })}>{t.name}</Chip>)}</div></div><Input placeholder="ماذا حدث؟" value={cr.note} onChange={(e) => setCr({ ...cr, note: e.target.value })} /><div className="grid grid-cols-2 gap-2"><Button variant="primary" size="lg" onClick={() => log("resisted")}>💪 قاومت</Button><Button variant="danger" size="lg" onClick={() => log("relapse")}>انتكست</Button></div><p className="text-[11px] text-muted">المحفز المتكرر (3+ مرات في أسبوع) يقلل XP المقاومة — إشارة لتغيير البيئة لا للجلد.</p></div>}</Card>
  </div>);
}

function RelapseTab() {
  const data = useApp((s) => s.data); const { confirm, dialog } = useConfirm(); const [open, setOpen] = useState(false);
  const [f, setF] = useState({ at: new Date().toISOString().slice(0, 16), durationMin: 10, acts: "", answers: {} as Record<string, string> });
  const gaps = relapseGaps(data.relapseLog); const sorted = [...data.relapseLog].sort((a, b) => b.at.localeCompare(a.at));
  const byMonth: Record<string, number> = {}; for (const r of data.relapseLog) byMonth[r.date.slice(0, 7)] = (byMonth[r.date.slice(0, 7)] ?? 0) + 1;
  return (<div className="space-y-3"><Grid cols={3}><StatCard label="إجمالي الأحداث" value={data.relapseLog.length} /><StatCard label="متوسط الفجوة" value={gaps.length ? `${Math.round(gaps.reduce((a, b) => a + b, 0) / gaps.length / 24)} يوم` : "—"} /><StatCard label="آخر 30 يوم" value={data.relapseLog.filter((r) => r.date >= todayISO().slice(0, 8) + "01").length} /></Grid>
    <Button variant="danger" onClick={() => setOpen(true)}>+ تسجيل انتكاس (بصدق)</Button>
    <BarSeries title="اتجاه شهري" data={Object.entries(byMonth).sort().slice(-12).map(([m, n]) => ({ m: m.slice(2), n }))} x="m" series={[{ key: "n", color: "var(--danger)", name: "انتكاسات" }]} height={180} />
    <div className="space-y-2">{sorted.map((r, i) => { const gapH = i < sorted.length - 1 ? (new Date(r.at).getTime() - new Date(sorted[i + 1].at).getTime()) / 3600000 : null; return <Card key={r.id} className="p-3"><div className="flex items-start justify-between"><div className="text-sm"><b>{r.at.slice(0, 16).replace("T", " ")}</b> · {r.durationMin} د{gapH != null && <span className="ms-2 text-xs text-muted">بعد {Math.round(gapH / 24)} يوم و{Math.round(gapH % 24)} س من السابق</span>}{r.acts.length > 0 && <div className="mt-1 flex flex-wrap gap-1">{r.acts.map((a) => <span key={a} className="rounded bg-surface-2 px-1.5 text-[10px]">{a}</span>)}</div>}{Object.entries(r.answers).filter(([, v]) => v).map(([q, v]) => <div key={q} className="mt-1 text-xs text-muted"><b>{data.relapseQuestions.find((x) => x.id === q)?.text}</b> {v}</div>)}</div><button type="button" aria-label="حذف" onClick={() => confirm("حذف السجل؟", () => recoveryActions.removeRelapse(r.id))}>🗑</button></div></Card>; })}{!sorted.length && <EmptyState icon="🕊️" title="لا انتكاسات مسجلة" />}</div>
    <Modal open={open} onClose={() => setOpen(false)} title="تسجيل انتكاس" footer={<Button variant="danger" onClick={() => { recoveryActions.relapse({ durationMin: f.durationMin, acts: f.acts.split(/[،,]/).map((s) => s.trim()).filter(Boolean), answers: f.answers }, new Date(f.at).toISOString()); setOpen(false); }}>تسجيل</Button>}><div className="space-y-3"><Grid><Field label="الوقت"><Input type="datetime-local" value={f.at} onChange={(e) => setF({ ...f, at: e.target.value })} /></Field><Field label="المدة (دقائق)"><Input type="number" value={f.durationMin} onChange={(e) => setF({ ...f, durationMin: Number(e.target.value) })} /></Field></Grid><Field label="الأفعال (مفصولة بفاصلة)"><Input value={f.acts} onChange={(e) => setF({ ...f, acts: e.target.value })} /></Field>{data.relapseQuestions.map((q) => <Field key={q.id} label={q.text}><Textarea value={f.answers[q.id] ?? ""} onChange={(e) => setF({ ...f, answers: { ...f.answers, [q.id]: e.target.value } })} /></Field>)}<p className="text-xs text-muted">يمكن تسجيل أكثر من حدث في اليوم. العدّاد يُعاد من آخر حدث.</p></div></Modal>{dialog}</div>);
}

function TasksTab() {
  const data = useApp((s) => s.data); const [t, setT] = useState(""); const [date, setDate] = useState(todayISO()); const s = sobrietyStats(data);
  const list = [...data.recoveryTasks].sort((a, b) => b.date.localeCompare(a.date));
  return (<div className="space-y-3"><Card title="مهام التعافي" subtitle={s.startAt && s.currentDays <= 30 ? "أول 30 يوم: المهمة الفائتة تُخصم −3 XP عند إغلاق اليوم" : "تظهر في «يومي» تلقائيًا"}><div className="grid gap-2 sm:grid-cols-[1fr_auto_auto]"><Input placeholder="مهمة صغيرة قابلة للتنفيذ…" value={t} onChange={(e) => setT(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && t.trim()) { recoveryActions.addTask(t.trim(), date); setT(""); } }} /><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /><Button variant="primary" disabled={!t.trim()} onClick={() => { recoveryActions.addTask(t.trim(), date); setT(""); }}>إضافة</Button></div></Card>
    <div className="space-y-1">{list.map((x) => <div key={x.id} className={cx("flex items-center gap-2 rounded-xl border p-2", x.done && "bg-ok/10")}><button type="button" role="checkbox" aria-checked={x.done} aria-label={x.title} onClick={() => recoveryActions.toggleTask(x)} className={cx("touch grid h-10 w-10 place-items-center rounded-lg border-2", x.done ? "border-transparent bg-ok text-white" : "")}>{x.done ? "✓" : ""}</button><div className="flex-1 text-sm"><div className={x.done ? "line-through opacity-60" : ""}>{x.title}</div><div className="text-[10px] text-muted">{x.date} · +{x.xp} XP</div></div><button type="button" aria-label="حذف" onClick={() => recoveryActions.removeTask(x.id)}>🗑</button></div>)}{!list.length && <EmptyState icon="🧩" title="لا مهام تعافٍ" description="مهام صغيرة: مشي 10 دقائق، اتصال بصديق، ترتيب الغرفة…" />}</div></div>);
}

function LostTab() {
  const data = useApp((s) => s.data); const [open, setOpen] = useState(false); const [f, setF] = useState({ title: "", plan: "", parts: "" }); const { confirm, dialog } = useConfirm();
  const statusOf = (l: LostThing) => { const rec = l.parts.filter((p) => p.status === "recovered").length; return l.parts.length ? Math.round((rec / l.parts.length) * 100) : 0; };
  return (<div className="space-y-3"><p className="text-xs text-muted">ما الذي أخذته منك هذه العادة؟ (ثقة، وقت، علاقة، صحة…) قسّمه إلى أجزاء واستردّه جزءًا جزءًا. كل جزء مسترد = XP.</p><Button variant="primary" onClick={() => setOpen(true)}>+ شيء فقدته</Button>
    {data.lostThings.map((l) => <Card key={l.id} title={l.title} subtitle={l.plan} action={<button type="button" aria-label="حذف" onClick={() => confirm("حذف؟", () => recoveryActions.removeLost(l.id))}>🗑</button>}><ProgressBar value={statusOf(l)} color="var(--gold)" label={l.title} className="mb-2" /><div className="space-y-1">{l.parts.map((p) => <div key={p.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-2 text-sm"><span className={p.status === "recovered" ? "line-through opacity-60" : ""}>{p.title} <span className="text-[10px] text-gold">+{p.xp}</span></span><Select value={p.status} onChange={(e) => recoveryActions.setPartStatus(l, p.id, e.target.value as "todo")} className="w-32 py-1"><option value="todo">لم يبدأ</option><option value="working">أعمل عليه</option><option value="recovered">استرددته</option></Select></div>)}</div></Card>)}
    {!data.lostThings.length && <EmptyState icon="🧭" title="لم تُسجل شيئًا بعد" />}
    <Modal open={open} onClose={() => setOpen(false)} title="ما الذي فقدته؟" footer={<Button variant="primary" onClick={() => { if (!f.title) return; recoveryActions.addLost(f.title, f.plan, f.parts.split("\n").map((s) => s.trim()).filter(Boolean)); setF({ title: "", plan: "", parts: "" }); setOpen(false); }}>حفظ</Button>}><div className="space-y-3"><Field label="الشيء"><Input value={f.title} onChange={(e) => setF({ ...f, title: e.target.value })} placeholder="مثال: ثقتي بنفسي" /></Field><Field label="خطة الاسترداد"><Textarea value={f.plan} onChange={(e) => setF({ ...f, plan: e.target.value })} /></Field><Field label="الأجزاء (سطر لكل جزء)"><Textarea value={f.parts} onChange={(e) => setF({ ...f, parts: e.target.value })} placeholder={"الوفاء بوعد صغير يوميًا\nإنهاء مشروع مؤجل\n..."} /></Field></div></Modal>{dialog}</div>);
}

function AnalyticsTab() {
  const data = useApp((s) => s.data); const a = useMemo(() => recoveryAnalytics(data), [data]); const s = sobrietyStats(data);
  const cal = Object.entries(a.calendar); const color = { clean: "var(--ok)", relapse: "var(--danger)", craving: "var(--warn)", none: "var(--surface-2)" };
  return (<div className="space-y-3"><Grid cols={4}><StatCard label="متوسط المزاج" value={a.avgMood.toFixed(1)} hint="30 يوم" /><StatCard label="متوسط الرغبة" value={a.avgUrge.toFixed(1)} /><StatCard label="رغبات مقاومة" value={`${a.resisted}/${a.cravings}`} tone="ok" /><StatCard label="إتمام الطقوس" value={`${a.ritualCompletion}%`} /><StatCard label="قراءات" value={a.checkIns} /><StatCard label="انتكاسات" value={a.relapses} tone="danger" /><StatCard label="متوسط الروحانية" value={a.avgSpiritual.toFixed(1)} /><StatCard label="معالم محققة" value={s.milestonesReached.length} tone="gold" /></Grid>
    <LineSeries title="منحنى التعافي (30 يوم)" data={a.curve.map((c) => ({ d: c.date.slice(5), mood: c.mood != null ? +c.mood.toFixed(1) : null, urge: c.urge != null ? +c.urge.toFixed(1) : null, index: c.index || null }))} x="d" series={[{ key: "mood", color: "var(--ok)", name: "المزاج" }, { key: "urge", color: "var(--danger)", name: "الرغبة" }, { key: "index", color: "var(--gold)", name: "المؤشر" }]} />
    <Card title="تقويم الشهر"><div className="grid grid-cols-10 gap-1">{cal.map(([d, st]) => <div key={d} title={`${d}: ${st}`} className="aspect-square rounded-md text-center text-[9px] leading-[1.9]" style={{ background: color[st] }}>{d.slice(8)}</div>)}</div><div className="mt-2 flex gap-3 text-[10px] text-muted"><span>🟩 نظيف</span><span>🟨 رغبة</span><span>🟥 انتكاس</span></div></Card>
    <Grid><Card title="المحفزات الأكثر تكرارًا">{a.triggers.length ? a.triggers.slice(0, 6).map((t) => <div key={t.name} className="mb-1"><div className="flex justify-between text-xs"><span>{t.name}</span><b>{t.count}</b></div><ProgressBar value={(t.count / a.triggers[0].count) * 100} color="var(--warn)" label={t.name} /></div>) : <p className="text-xs text-muted">لا بيانات.</p>}</Card><Card title="الأيام الصعبة">{a.hardDays.length ? <ul className="space-y-1 text-sm">{a.hardDays.map((d) => <li key={d.date} className="flex justify-between rounded-xl bg-surface-2 px-3 py-1.5"><span>{formatShort(d.date)} ({WEEKDAY_SHORT_AR[weekday(d.date)]})</span><b className="text-danger">رغبة {d.urge}</b></li>)}</ul> : <p className="text-xs text-muted">لا أيام برغبة ≥7.</p>}</Card></Grid>
    <Card title="المعالم"><div className="flex flex-wrap gap-1.5">{SOBRIETY_MILESTONES.map((m) => <span key={m} className={cx("rounded-full px-2.5 py-1 text-xs font-bold", s.currentDays >= m ? "bg-gold text-black" : "bg-surface-2 text-muted")}>{m} يوم</span>)}</div></Card>
    <Disclaimer>{RECOVERY_DISCLAIMER}</Disclaimer></div>);
}
function PhaseTab({ days }: { days: number }) {
  const cur = recoveryPhase(days);
  return (<div className="space-y-3">{PHASES.map((p) => <Card key={p.id} title={`${p.label} · ${p.range}`} subtitle={p.focus} tone={p.id === cur.id ? "gold" : undefined}>{p.id === cur.id && <span className="mb-2 inline-block rounded-full bg-gold-soft px-2 py-0.5 text-xs font-bold text-gold">مرحلتك الحالية</span>}<ul className="list-inside list-disc space-y-1 text-sm">{p.guidance.map((g) => <li key={g}>{g}</li>)}</ul><p className="mt-2 rounded-xl bg-warn/10 px-3 py-2 text-xs text-warn">⚠ {p.warning}</p></Card>)}</div>);
}
