"use client";
import React, { useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useApp, useLevel } from "@/stores/app-store";
import { identityActions } from "@/stores/actions";
import { AREAS, IdentityPrinciple } from "@/types/app-data";
import { areaScores, rankForLevel, RANK_LABEL, totalXp, weightedAreaScore, xpByArea, xpForLevel } from "@/calculations/gamification";
import { bodyProgress, overallBodyProgress, resizeImage, latestValue } from "@/calculations/body";
import { quranProgress } from "@/calculations/quran";
import { sobrietyStats } from "@/calculations/recovery";
import { lifetimeAverages } from "@/calculations/goals";
import { addDays, todayISO, uid } from "@/core/date";
import { Button, Card, EmptyState, Field, Grid, Input, Modal, ProgressBar, RankBadge, StatCard, Tabs, Textarea, useConfirm, XPBadge, cx } from "@/components/ui";
import { RadarSeries, BarSeries } from "@/components/charts";

export default function MePage() {
  const sp = useSearchParams(); const [tab, setTab] = useState<"card" | "areas" | "identity">((sp?.get("tab") as "identity") || "card");
  return (<div className="space-y-4 anim-fade-up"><Tabs value={tab} onChange={setTab} tabs={[{ id: "card", label: "🛡️ بطاقة اللاعب" }, { id: "areas", label: "⚖️ توازن الحياة" }, { id: "identity", label: "🧭 الهوية" }]} />{tab === "card" && <PlayerCard />}{tab === "areas" && <AreasTab />}{tab === "identity" && <IdentityTab />}</div>);
}

function PlayerCard() {
  const data = useApp((s) => s.data); const update = useApp((s) => s.update); const lvl = useLevel(); const rank = rankForLevel(lvl.level); const total = totalXp(data.xpLog); const avatarRef = useRef<HTMLInputElement>(null); const cardRef = useRef<HTMLInputElement>(null);
  const bp = bodyProgress(data.bodyEntries, data.goalSettings); const q = quranProgress(data.quranMemorization, todayISO()); const sob = sobrietyStats(data); const life = lifetimeAverages(data);
  const savings = data.savingsEntries.reduce((a, s) => a + s.amount, 0); const month = todayISO().slice(0, 7); const income = data.financeEntries.filter((f) => f.type === "income" && f.date.startsWith(month)).reduce((a, f) => a + f.amount, 0);
  const goalBars = [{ label: "الجسم", v: overallBodyProgress(bp) }, { label: "حفظ القرآن", v: Math.min(100, Math.round((q.memorized / Math.max(1, data.goalSettings.quranMemGoalPages)) * 100)) }, { label: "الادخار", v: data.goalSettings.savingsGoal ? Math.min(100, Math.round((savings / data.goalSettings.savingsGoal) * 100)) : 0 }, { label: "الدخل الشهري", v: data.goalSettings.incomeGoal ? Math.min(100, Math.round((income / data.goalSettings.incomeGoal) * 100)) : 0 }];
  const combined = Math.round(goalBars.reduce((a, g) => a + g.v, 0) / goalBars.length);
  return (<div className="space-y-3">
    <div className="card relative overflow-hidden p-0"><div className="h-36 bg-gradient-to-br from-accent/40 via-surface-2 to-gold/30" style={data.profileCardPhoto ? { backgroundImage: `url(${data.profileCardPhoto})`, backgroundSize: "cover", backgroundPosition: "center" } : undefined} /><button type="button" className="absolute end-3 top-3 rounded-lg bg-black/40 px-2 py-1 text-[11px] text-white" onClick={() => cardRef.current?.click()}>تغيير الغلاف</button><input ref={cardRef} type="file" accept="image/*" className="hidden" onChange={async (e) => { const f = e.target.files?.[0]; if (f) { const url = await resizeImage(f, 1200); update("profileCardPhoto", () => url); } }} />
      <div className="-mt-12 flex items-end gap-4 px-5 pb-5"><button type="button" onClick={() => avatarRef.current?.click()} className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-3xl border-4 border-surface bg-surface-2 text-4xl shadow-xl" aria-label="تغيير الصورة">{data.profileAvatar ? <img src={data.profileAvatar} alt="" className="h-full w-full object-cover" /> : "🛡️"}</button><input ref={avatarRef} type="file" accept="image/*" className="hidden" onChange={async (e) => { const f = e.target.files?.[0]; if (f) { const url = await resizeImage(f, 400); update("profileAvatar", () => url); } }} /><div className="min-w-0 flex-1 pb-1"><div className="text-2xl font-black">{data.bodyProfile.name || "الفارس الفارغ"}</div><div className="text-xs text-muted">{RANK_LABEL[rank]} · Lv {lvl.level} · {total} XP · {life.totalDays} يوم مسجل</div></div><RankBadge rank={rank} level={lvl.level} size="lg" /></div>
      <div className="px-5 pb-5"><ProgressBar value={lvl.progress * 100} color="var(--gold)" height={10} label="تقدم المستوى" /><div className="mt-1 flex justify-between text-[11px] text-muted"><span>{lvl.current}/{lvl.needed} XP للمستوى {lvl.level + 1}</span><span>الرتبة التالية عند Lv {rank === "S" ? "—" : [10, 20, 30, 40, 50].find((l) => l > lvl.level)} ({xpForLevel([10, 20, 30, 40, 50].find((l) => l > lvl.level) ?? 50)} XP)</span></div></div></div>
    <Card title="التقدم المجمّع" subtitle={`متوسط ${combined}% عبر الأهداف الكبرى`}><div className="space-y-2">{goalBars.map((g) => <div key={g.label}><div className="flex justify-between text-xs"><span>{g.label}</span><b>{g.v}%</b></div><ProgressBar value={g.v} label={g.label} color={g.v >= 100 ? "var(--gold)" : "var(--accent)"} /></div>)}</div></Card>
    <Grid cols={4}><StatCard label="ملخص الجسم" value={latestValue(data.bodyEntries, "weight") ? `${latestValue(data.bodyEntries, "weight")} كجم` : "—"} hint={`تقدم ${overallBodyProgress(bp)}%`} icon="🏋️" /><StatCard label="القرآن" value={`${q.memorized} ص`} hint={`${q.units} وحدة · ${q.dueReviews} مستحقة`} icon="📖" tone="ok" /><StatCard label="المال" value={savings} hint={`ادخار · دخل الشهر ${income}`} icon="💰" tone="gold" /><StatCard label="التعافي" value={sob.startAt ? `${sob.currentDays} يوم` : "—"} hint={sob.startAt ? `الأطول ${sob.longestDays}` : ""} icon="🌱" /></Grid>
    <Card title="الاسم"><Input value={data.bodyProfile.name ?? ""} onChange={(e) => update("bodyProfile", (b) => ({ ...b, name: e.target.value }))} placeholder="اسم اللاعب" /></Card>
  </div>);
}

function AreasTab() {
  const data = useApp((s) => s.data); const w = data.goalSettings.areaWeights; const today = todayISO();
  const life = useMemo(() => areaScores(data.xpLog, w), [data.xpLog, w]); const month = useMemo(() => areaScores(data.xpLog, w, addDays(today, -29), today), [data.xpLog, w, today]); const week = useMemo(() => areaScores(data.xpLog, w, addDays(today, -6), today), [data.xpLog, w, today]);
  const radar = AREAS.map((a) => ({ axis: a.label, lifetime: life[a.id], month: month[a.id], week: week[a.id] })); const xpArea = xpByArea(data.xpLog);
  const trend = useMemo(() => Array.from({ length: 8 }, (_, i) => { const end = addDays(today, -7 * (7 - i)); const s = xpByArea(data.xpLog, addDays(end, -6), end); return { w: end.slice(5), ...s }; }), [data.xpLog, today]);
  return (<div className="space-y-3"><Grid><RadarSeries title="رادار توازن الحياة" subtitle={`الدرجة الموزونة: ${weightedAreaScore(life, w)}`} data={radar} series={[{ key: "lifetime", color: "var(--gold)", name: "عمري" }, { key: "month", color: "var(--accent)", name: "30 يوم" }, { key: "week", color: "#10b981", name: "7 أيام" }]} /><Card title="مقارنة المحاور"><div className="space-y-2">{AREAS.map((a) => <div key={a.id}><div className="flex justify-between text-xs"><span>{a.emoji} {a.label} <span className="text-muted">وزن ×{w[a.id]}</span></span><span><b>{xpArea[a.id]}</b> XP · {life[a.id]}</span></div><ProgressBar value={life[a.id]} color={a.color} label={a.label} /></div>)}</div></Card></Grid>
    <BarSeries title="XP لكل محور — آخر 8 أسابيع" data={trend} x="w" series={AREAS.map((a) => ({ key: a.id, color: a.color, name: a.label }))} stacked height={240} /></div>);
}

function IdentityTab() {
  const data = useApp((s) => s.data); const { confirm, dialog } = useConfirm(); const [edit, setEdit] = useState<Partial<IdentityPrinciple> | null>(null); const today = todayISO();
  const save = () => { if (!edit?.title?.trim()) return; const p = { title: edit.title.trim(), statement: edit.statement ?? "", recoveryFocus: edit.recoveryFocus ?? "", lostItemIds: edit.lostItemIds ?? [], rules: edit.rules ?? [], practices: edit.practices ?? [] }; if (edit.id) identityActions.update(edit.id, p); else identityActions.add(p); setEdit(null); };
  const [newRule, setNewRule] = useState(""); const [newPractice, setNewPractice] = useState({ title: "", xp: 5 });
  return (<div className="space-y-3"><p className="text-xs text-muted">مبادئ الهوية: من أنت عندما لا يراك أحد؟ كل مبدأ له عبارة، تركيز تعافٍ، قواعد، وممارسات يومية تُكسب XP.</p><Button variant="primary" onClick={() => setEdit({ practices: [], rules: [], lostItemIds: [] })}>+ مبدأ</Button>
    {data.identityPrinciples.length === 0 && <EmptyState icon="🧭" title="لا مبادئ بعد" description="مثال: «أنا رجل يفي بوعوده الصغيرة» — قاعدة: لا أؤجل ما يستغرق دقيقتين. ممارسة: إنجاز وعد صغير قبل النوم." />}
    {data.identityPrinciples.map((p) => <Card key={p.id} title={p.title} subtitle={p.statement} action={<div className="flex gap-1"><Button size="sm" onClick={() => setEdit(p)}>تعديل</Button><Button size="sm" variant="ghost" onClick={() => confirm("حذف المبدأ؟", () => identityActions.remove(p.id))}>🗑</Button></div>}>{p.recoveryFocus && <p className="mb-2 rounded-xl bg-ok/10 px-3 py-1.5 text-xs">🌱 تركيز التعافي: {p.recoveryFocus}</p>}{p.lostItemIds.length > 0 && <div className="mb-2 flex flex-wrap gap-1 text-[11px]">{p.lostItemIds.map((id) => <span key={id} className="rounded-full bg-gold-soft px-2 text-gold">↺ {data.lostThings.find((l) => l.id === id)?.title ?? "—"}</span>)}</div>}{p.rules.length > 0 && <ul className="mb-2 list-inside list-disc text-sm">{p.rules.map((r, i) => <li key={i}>{r}</li>)}</ul>}<div className="space-y-1">{p.practices.map((pr) => { const done = pr.log.includes(today); return <div key={pr.id} className={cx("flex items-center gap-2 rounded-xl border p-2", done && "bg-ok/10")}><button type="button" role="checkbox" aria-checked={done} aria-label={pr.title} disabled={done} onClick={() => identityActions.logPractice(p.id, pr.id)} className={cx("touch grid h-10 w-10 place-items-center rounded-lg border-2", done && "border-transparent bg-ok text-white")}>{done ? "✓" : ""}</button><span className="flex-1 text-sm">{pr.title}</span><XPBadge xp={pr.xp} small /><span className="text-[10px] text-muted">{pr.log.length} مرة</span></div>; })}</div></Card>)}
    <Modal open={!!edit} onClose={() => setEdit(null)} title={edit?.id ? "تعديل المبدأ" : "مبدأ جديد"} size="lg" footer={<Button variant="primary" onClick={save}>حفظ</Button>}>{edit && <div className="space-y-3"><Field label="العنوان"><Input value={edit.title ?? ""} onChange={(e) => setEdit({ ...edit, title: e.target.value })} /></Field><Field label="العبارة (أنا…)"><Textarea value={edit.statement ?? ""} onChange={(e) => setEdit({ ...edit, statement: e.target.value })} /></Field><Field label="تركيز التعافي"><Input value={edit.recoveryFocus ?? ""} onChange={(e) => setEdit({ ...edit, recoveryFocus: e.target.value })} /></Field>
      {data.lostThings.length > 0 && <Field label="مرتبط بما فقدته"><div className="flex flex-wrap gap-1">{data.lostThings.map((l) => { const on = edit.lostItemIds?.includes(l.id); return <button key={l.id} type="button" aria-pressed={on} onClick={() => setEdit({ ...edit, lostItemIds: on ? edit.lostItemIds!.filter((x) => x !== l.id) : [...(edit.lostItemIds ?? []), l.id] })} className={cx("touch rounded-full border px-3 py-1 text-xs", on && "bg-accent text-white")}>{l.title}</button>; })}</div></Field>}
      <Field label="القواعد"><ul className="mb-1 space-y-1 text-sm">{(edit.rules ?? []).map((r, i) => <li key={i} className="flex justify-between rounded-lg bg-surface-2 px-2 py-1">{r}<button type="button" onClick={() => setEdit({ ...edit, rules: edit.rules!.filter((_, j) => j !== i) })}>✕</button></li>)}</ul><div className="flex gap-1"><Input value={newRule} onChange={(e) => setNewRule(e.target.value)} placeholder="قاعدة…" /><Button onClick={() => { if (newRule.trim()) { setEdit({ ...edit, rules: [...(edit.rules ?? []), newRule.trim()] }); setNewRule(""); } }}>+</Button></div></Field>
      <Field label="الممارسات (تدخل في XP)"><ul className="mb-1 space-y-1 text-sm">{(edit.practices ?? []).map((p, i) => <li key={p.id} className="flex justify-between rounded-lg bg-surface-2 px-2 py-1">{p.title} <span>+{p.xp} <button type="button" onClick={() => setEdit({ ...edit, practices: edit.practices!.filter((_, j) => j !== i) })}>✕</button></span></li>)}</ul><div className="flex gap-1"><Input value={newPractice.title} onChange={(e) => setNewPractice({ ...newPractice, title: e.target.value })} placeholder="ممارسة…" /><Input type="number" className="w-20" value={newPractice.xp} onChange={(e) => setNewPractice({ ...newPractice, xp: Number(e.target.value) })} /><Button onClick={() => { if (newPractice.title.trim()) { setEdit({ ...edit, practices: [...(edit.practices ?? []), { id: uid("pr"), title: newPractice.title.trim(), xp: newPractice.xp, log: [] }] }); setNewPractice({ title: "", xp: 5 }); } }}>+</Button></div></Field></div>}</Modal>{dialog}
  </div>);
}
