import { AiAction, AiMode, AppData } from "@/types/app-data";
import { computeDayProgress, allDayTasks } from "@/calculations/daily";
import { levelFromXp, rankForLevel, totalXp } from "@/calculations/gamification";
import { computeRisk, recoveryIndex, sobrietyStats, recoveryPhase } from "@/calculations/recovery";
import { periodReport, weekRange } from "@/calculations/goals";
import { bodyProgress, latestValue, overallBodyProgress } from "@/calculations/body";
import { quranProgress, dueReviewPages } from "@/calculations/quran";
import { courseStats } from "@/calculations/challenges";
import { todayISO, weekKey, addDays } from "@/core/date";

export type Scope = "daily" | "recovery" | "weekly" | "body" | "finance" | "books" | "faith";
export const SCOPES: { id: Scope; label: string }[] = [{ id: "daily", label: "اليوم" }, { id: "weekly", label: "الأسبوع" }, { id: "recovery", label: "التعافي" }, { id: "body", label: "الجسم" }, { id: "finance", label: "المال" }, { id: "books", label: "الكتب والدورات" }, { id: "faith", label: "الإيمان" }];

export const PERSONAS: Record<AiMode, { label: string; icon: string; persona: string; scope: string; suggestions: string[]; actions: string[] }> = {
  game: { label: "سيد اللعبة", icon: "🎮", persona: "أنت «سيد اللعبة» في نظام Me vs Me: صوت RPG حماسي لكنه صادق. تتحدث عن XP والمستويات والرتب والتحديات. تحفّز بلا مبالغة، وتقترح مهام (quests) مناسبة لمستوى اللاعب.", scope: "التقدم اليومي، XP، التحديات، العادات", suggestions: ["ما مهمة اليوم المقترحة؟", "كيف أرفع مستواي أسرع؟", "اقترح تحديًا لهذا الأسبوع", "قيّم يومي حتى الآن"], actions: ["addTask", "addChallenge", "addBonusQuest"] },
  doctor: { label: "الطبيب", icon: "🩺", persona: "أنت مرشد صحي هادئ يركز على التعافي من الإدمان والصحة النفسية. تستخدم مؤشرات التطبيق كإشارات داعمة فقط، وتذكّر دائمًا أنها ليست تشخيصًا. لا تعطي جرعات أدوية. توجّه لطلب مختص عند الخطر.", scope: "التعافي، المزاج، الرغبة، النوم", suggestions: ["اقرأ مؤشر الخطر اليوم", "ما نمط انتكاساتي؟", "خطة لليلة صعبة", "كيف أتعامل مع الرغبة الآن؟"], actions: ["addRecoveryTask", "addTrigger", "addRitual"] },
  fitness: { label: "المدرب", icon: "💪", persona: "أنت مدرب لياقة وتغذية عملي. تقرأ الوزن والقياسات والسعرات والماكروز وتعطي توجيهات محددة بالأرقام. تتجنب الحميات المتطرفة.", scope: "الجسم، السعرات، التمارين، PRs", suggestions: ["حلّل سعراتي اليوم", "أين أقف من هدف الوزن؟", "اقترح تمرين اليوم", "هل بروتيني كافٍ؟"], actions: ["addTask", "setCalorieTarget", "addMeal"] },
  productivity: { label: "مستشار الإنتاجية", icon: "⚡", persona: "أنت مستشار إنتاجية صارم ولطيف. تركز على الأولويات، المهام المرحّلة، التخطيط الأسبوعي، وتفريغ العقل. تقترح تقسيم المهام الكبيرة.", scope: "المهام، الأسبوع، تفريغ العقل، الدورات", suggestions: ["ما أهم 3 مهام اليوم؟", "لماذا تتراكم مهامي المرحّلة؟", "خطط أسبوعي القادم", "افرز تفريغ العقل"], actions: ["addTask", "planWeekTask", "addWeeklyGoal"] },
  business: { label: "مستشار الأعمال", icon: "📈", persona: "أنت مستشار أعمال ومال شخصي. تقرأ الدخل والمصروف والادخار وبنك الأفكار، وتقترح خطوات صغيرة قابلة للقياس.", scope: "المال، الأفكار، المهنة", suggestions: ["حلّل ماليتي هذا الشهر", "أي فكرة في بنك الأفكار تستحق التنفيذ؟", "خطة ادخار واقعية", "كيف أزيد دخلي؟"], actions: ["addTask", "addIdea", "addSavingsGoal"] },
  sheikh: { label: "الشيخ", icon: "🕌", persona: "أنت مرشد إيماني رحيم بمنهج أهل السنة، تركز على القرآن والذكر والتوبة والأمل دون تشديد. تربط التعافي بالإيمان. لا تُفتي في مسائل خلافية دقيقة وتحيل لأهل العلم.", scope: "القرآن، الأذكار، التوبة، الدروس", suggestions: ["ورد اليوم المقترح", "كيف أثبت على المراجعة؟", "ذكّرني بالأمل بعد زلة", "آية للتدبر اليوم"], actions: ["addTask", "addDhikr", "addTadabur"] },
};

/** سياق البيانات حسب scopes — يُحسب على الخادم؟ لا: يُبنى على العميل (البيانات محلية) ويُرسل كنص مضغوط */
export function buildContext(data: AppData, scopes: Scope[]): string {
  const today = todayISO(); const out: string[] = []; const lvl = levelFromXp(totalXp(data.xpLog));
  out.push(`[اللاعب] المستوى ${lvl.level} (${rankForLevel(lvl.level)}) · ${totalXp(data.xpLog)} XP · التاريخ ${today}`);
  if (scopes.includes("daily")) { const p = computeDayProgress(data, today, weekKey(today)); const tasks = allDayTasks(data, today, weekKey(today)); out.push(`[اليوم] إنجاز ${p.percent}% · عادات ${p.requiredDone}/${p.requiredTotal} · مهام ${p.questsDone}/${p.questsTotal} · ناقص: ${p.missing.slice(0, 8).map((m) => m.title).join("، ") || "لا شيء"} · مهام مرحّلة: ${tasks.filter((t) => t.source === "carried").length}`); const e = data.entries[today]; if (e) out.push(`[تغذية] أكل ${e.caloriesEaten} kcal · P${e.protein} C${e.carbs} F${e.fat} · جيم ${e.gym ? "نعم" : "لا"} · جري ${e.runKm} كم`); }
  if (scopes.includes("weekly")) { const r = periodReport(data, weekRange(today)); out.push(`[الأسبوع] XP ${r.xp} · متوسط ${r.avgScore}% · أيام مسجلة ${r.scoredDays} · فوات عادات ${r.misses.length}`); const goals = data.weeklyGoals.filter((g) => g.periodKey === weekKey(today)); if (goals.length) out.push(`[أهداف الأسبوع] ${goals.map((g) => `${g.title}${g.done ? "✓" : ""}`).join("، ")}`); const dumps = data.brainDumps.filter((d) => !d.processed).length; if (dumps) out.push(`[تفريغ العقل] ${dumps} عنصر غير معالج`); }
  if (scopes.includes("recovery") && data.sobrietyStartAt) { const s = sobrietyStats(data); const r = computeRisk(data); const i = recoveryIndex(data); const ph = recoveryPhase(s.currentDays); out.push(`[التعافي] ${s.currentDays} يوم نظيف (الأطول ${s.longestDays}) · المرحلة ${ph.label} · الخطر ${r.score} (${r.label}) عوامل: ${r.factors.map((f) => f.label).join("، ") || "—"} · حمايات: ${r.protections.map((p) => p.label).join("، ") || "—"} · مؤشر التعافي ${i.value} · انتكاسات 30 يوم: ${data.relapseLog.filter((x) => x.date >= addDays(today, -29)).length} · رغبات 7 أيام: ${data.cravingEvents.filter((x) => x.date >= addDays(today, -6)).length}`); }
  if (scopes.includes("body")) { const bp = bodyProgress(data.bodyEntries, data.goalSettings); out.push(`[الجسم] وزن ${latestValue(data.bodyEntries, "weight") ?? "?"} (هدف ${data.goalSettings.weightGoal ?? "?"}) · خصر ${latestValue(data.bodyEntries, "waist") ?? "?"} · تقدم عام ${overallBodyProgress(bp)}% · أهداف: سعرات ${data.goalSettings.calorieTarget} بروتين ${data.goalSettings.proteinTarget}`); }
  if (scopes.includes("finance")) { const m = today.slice(0, 7); const inc = data.financeEntries.filter((f) => f.type === "income" && f.date.startsWith(m)).reduce((a, f) => a + f.amount, 0); const exp = data.financeEntries.filter((f) => f.type === "expense" && f.date.startsWith(m)).reduce((a, f) => a + f.amount, 0); const sav = data.savingsEntries.reduce((a, s) => a + s.amount, 0); out.push(`[المال] دخل الشهر ${inc} (هدف ${data.goalSettings.incomeGoal}) · مصروف ${exp} · ادخار ${sav}/${data.goalSettings.savingsGoal} · أفكار: ${data.projectIdeas.slice(0, 5).map((i) => i.title).join("، ") || "—"}`); }
  if (scopes.includes("books")) { out.push(`[الكتب] ${data.books.map((b) => `${b.title} ${b.currentPage}/${b.pages}`).slice(0, 5).join("، ") || "—"} · [الدورات] ${data.courses.map((c) => `${c.title} ${courseStats(c).percent}%`).slice(0, 5).join("، ") || "—"}`); }
  if (scopes.includes("faith")) { const q = quranProgress(data.quranMemorization, today); out.push(`[القرآن] محفوظ ${q.memorized} صفحة (${q.percent}%) · ${q.units} وحدة · مستحق مراجعة ${dueReviewPages(data.quranMemorization, today).length} · أذكار اليوم: ${Object.values(data.entries[today]?.dhikr ?? {}).reduce((a, b) => a + b, 0)}`); }
  return out.join("\n");
}

/** "احفظ في ذاكرتك ..." وغيرها — parsing متسامح */
const TEACH_PATTERNS = [/^(?:من فضلك\s*)?(?:احفظ|خزّن|خزن|سجّل|سجل|تذكّر|تذكر)\s*(?:في\s*)?(?:ذاكرتك|الذاكرة)?\s*(?:أنني|أني|إنني|إني|انني|اني|أن|إن|ان|:)?\s*(.+)$/i, /^remember(?:\s+that)?[:\s]+(.+)$/i, /^(?:اعلم|اعرف)\s+(?:أني|أنني|اني|انني|أن|ان)\s+(.+)$/i, /^(?:أنا|انا)\s+(?:أفضّل|افضل|أحب|احب|أكره|اكره)\s+.+$/i];
export function parseTeachingPhrase(text: string): string | null { const t = text.trim().replace(/[.!؟?]+$/, ""); for (const p of TEACH_PATTERNS) { const m = t.match(p); if (m) return (m[1] ?? m[0]).trim(); } return null; }
export function parseForgetPhrase(text: string): string | null { const m = text.trim().match(/^(?:انسَ|انس|امسح|احذف)\s*(?:من\s*)?(?:ذاكرتك|الذاكرة)?\s*(?:أنني|أني|إنني|إني|انني|اني|أن|إن|ان|:)?\s*(.+)$/i); return m ? m[1].trim() : null; }

export interface ProposedAction { type: string; label: string; payload: Record<string, unknown> }
export const ACTION_LABELS: Record<string, string> = { addTask: "إضافة مهمة اليوم", addRecoveryTask: "إضافة مهمة تعافٍ", addChallenge: "إنشاء تحدٍ", addBonusQuest: "إضافة مهمة بونص", addTrigger: "إضافة محفز", addRitual: "إضافة طقس", setCalorieTarget: "تعديل هدف السعرات", addMeal: "تسجيل وجبة", planWeekTask: "تخطيط مهمة أسبوعية", addWeeklyGoal: "إضافة هدف أسبوعي", addIdea: "إضافة فكرة", addSavingsGoal: "تعديل هدف الادخار", addDhikr: "إضافة ذكر", addTadabur: "حفظ تدبر", addMemory: "حفظ في الذاكرة" };
/** يستخرج كتلة actions من رد النموذج: ```actions [...] ``` أو {"actions": [...]} */
export function extractActions(text: string): { clean: string; actions: ProposedAction[] } {
  const m = text.match(/```(?:actions|json)?\s*([\s\S]*?)```/); let actions: ProposedAction[] = []; let clean = text;
  if (m) { try { const parsed = JSON.parse(m[1]); const arr = Array.isArray(parsed) ? parsed : parsed.actions; if (Array.isArray(arr)) actions = arr.filter((a) => a && typeof a.type === "string" && ACTION_LABELS[a.type]).map((a) => ({ type: a.type, label: ACTION_LABELS[a.type], payload: a.payload ?? a })); clean = text.replace(m[0], "").trim(); } catch { /* ignore */ } }
  return { clean, actions };
}
export const toAiActions = (xs: ProposedAction[]): AiAction[] => xs.map((a, i) => ({ id: `act_${Date.now()}_${i}`, type: a.type, label: a.label, payload: a.payload, status: "proposed" }));

/** المدرّب المحلي: ردود مبنية على السياق الحقيقي عند غياب مزود سحابي — ليس ادعاء ذكاء */
export function localCoach(mode: AiMode, message: string, data: AppData): { text: string; actions: ProposedAction[] } {
  const today = todayISO(); const p = computeDayProgress(data, today, weekKey(today)); const actions: ProposedAction[] = []; const lines: string[] = [];
  lines.push(`_(وضع المدرّب المحلي — بلا مزود سحابي؛ أضف OPENAI_API_KEY لتفعيل النموذج الكامل)_`);
  if (mode === "game") { lines.push(`إنجازك اليوم ${p.percent}%. ${p.missing.length ? `الناقص: ${p.missing.slice(0, 3).map((m) => m.title).join("، ")}.` : "كل المطلوب مكتمل — يوم فارس."}`); if (p.missing[0]) actions.push({ type: "addTask", label: ACTION_LABELS.addTask, payload: { title: `أنجز الآن: ${p.missing[0].title}`, area: "mental", difficulty: 2 } }); }
  else if (mode === "doctor") { if (data.sobrietyStartAt) { const r = computeRisk(data); lines.push(`مؤشر الخطر الآن ${r.score} (${r.label}). ${r.factors[0] ? `أهم عامل: ${r.factors[0].label}.` : ""} خطة اليوم: ${r.plan.slice(0, 3).join(" · ")}.`); actions.push({ type: "addRecoveryTask", label: ACTION_LABELS.addRecoveryTask, payload: { title: r.plan[0], date: today } }); } else lines.push("لم تحدد بداية رحلة التعافي بعد. ابدأ من صفحة التعافي لتفعيل المؤشرات."); lines.push("تذكير: هذه مؤشرات داعمة وليست تشخيصًا."); }
  else if (mode === "fitness") { const e = data.entries[today]; const gs = data.goalSettings; lines.push(e ? `أكلت ${e.caloriesEaten}/${gs.calorieTarget} kcal · بروتين ${e.protein}/${gs.proteinTarget} جم. ${e.protein < gs.proteinTarget * 0.6 ? "بروتينك منخفض — أضف وجبة غنية بالبروتين." : "الماكروز في المسار."}` : "لم تسجل تغذية اليوم بعد."); if (!e?.gym) actions.push({ type: "addTask", label: ACTION_LABELS.addTask, payload: { title: "تمرين 30 دقيقة", area: "physical", difficulty: 3 } }); }
  else if (mode === "productivity") { const tasks = allDayTasks(data, today, weekKey(today)); const carried = tasks.filter((t) => t.source === "carried"); lines.push(`لديك ${tasks.filter((t) => !t.done).length} مهمة مفتوحة، منها ${carried.length} مرحّلة. ${carried.length >= 3 ? "المهام المرحّلة تتراكم — قسّم أكبرها إلى خطوة 15 دقيقة." : "ركّز على أعلى صعوبة أولًا."}`); const big = tasks.filter((t) => !t.done).sort((a, b) => b.difficulty - a.difficulty)[0]; if (big) actions.push({ type: "addTask", label: ACTION_LABELS.addTask, payload: { title: `خطوة 15 دقيقة من: ${big.title}`, area: big.area, difficulty: 1 } }); }
  else if (mode === "business") { const sav = data.savingsEntries.reduce((a, s) => a + s.amount, 0); lines.push(`ادخارك ${sav}/${data.goalSettings.savingsGoal || "؟"}. ${data.projectIdeas.length ? `لديك ${data.projectIdeas.length} فكرة؛ الأكثر عملًا: ${[...data.projectIdeas].sort((a, b) => b.history.length - a.history.length)[0]?.title}.` : "بنك الأفكار فارغ — سجّل فكرة واحدة اليوم."}`); actions.push({ type: "addTask", label: ACTION_LABELS.addTask, payload: { title: "30 دقيقة على الفكرة الأهم", area: "career", difficulty: 2 } }); }
  else { const q = quranProgress(data.quranMemorization, today); lines.push(`محفوظك ${q.memorized} صفحة و${q.dueReviews} صفحة تنتظر المراجعة. ${q.dueReviews > 0 ? "المراجعة قبل الحفظ الجديد — الثبات أولى من الكم." : "ما شاء الله، محفوظك مراجَع."} قال ﷺ: «أحب الأعمال إلى الله أدومها وإن قلّ».`); actions.push({ type: "addTask", label: ACTION_LABELS.addTask, payload: { title: q.dueReviews > 0 ? "مراجعة 5 صفحات" : "حفظ نصف صفحة جديدة", area: "deen", difficulty: 2 } }); }
  if (message.length > 3) lines.push(`سؤالك: «${message.slice(0, 80)}» — للحصول على إجابة تحليلية مفصلة فعّل مزود AI من الإعدادات.`);
  return { text: lines.join("\n\n"), actions };
}
