"use client";
import React, { useMemo, useState } from "react";
import { useApp } from "@/stores/app-store";
import { quranActions } from "@/stores/actions";
import { dueReviewPages, JUZ_COUNT, pagesOfJuz, QURAN_PAGES, QURAN_UNITS, quranProgress, reviewWarning, juzOfPage } from "@/calculations/quran";
import { todayISO } from "@/core/date";
import { Button, Card, Chip, EmptyState, Field, Grid, Input, ProgressBar, ProgressRing, StatCard, Textarea, cx, useConfirm } from "@/components/ui";

export default function QuranPage() {
  const data = useApp((s) => s.data); const update = useApp((s) => s.update); const q = data.quranMemorization; const today = todayISO();
  const p = useMemo(() => quranProgress(q, today), [q, today]); const due = useMemo(() => dueReviewPages(q, today), [q, today]); const warn = reviewWarning(q, today);
  const [juz, setJuz] = useState(() => { const pages = Object.keys(q.pages).map(Number); return pages.length ? juzOfPage(Math.max(...pages)) : 30; }); const [tad, setTad] = useState({ ref: "", text: "" }); const { confirm, dialog } = useConfirm();
  const pages = pagesOfJuz(juz);
  return (<div className="space-y-4 anim-fade-up">
    <Card className="flex flex-wrap items-center gap-4"><ProgressRing value={p.percent} size={96} color="var(--ok)" label="نسبة الحفظ" /><div className="flex-1"><div className="text-lg font-black">القرآن الكريم</div><div className="text-xs text-muted">{QURAN_PAGES} صفحة · {QURAN_UNITS} وحدة (ربع حزب)</div><Grid cols={4} className="mt-2"><StatCard label="محفوظ" value={p.memorized} hint="صفحة" tone="ok" /><StatCard label="وحدات" value={`${p.units}/${QURAN_UNITS}`} /><StatCard label="مستحق للمراجعة" value={p.dueReviews} tone={warn.level === "danger" ? "danger" : warn.level === "warn" ? "warn" : undefined} /><StatCard label="متقن (5+ مراجعات)" value={p.strongPages} tone="gold" /></Grid><ProgressBar value={(p.memorized / Math.max(1, data.goalSettings.quranMemGoalPages)) * 100} color="var(--ok)" className="mt-2" label="تقدم هدف الحفظ" /><div className="text-[11px] text-muted">هدفك: {data.goalSettings.quranMemGoalPages} صفحة</div></div></Card>
    {warn.level !== "ok" && <div role="alert" className={cx("rounded-2xl border px-4 py-3 text-sm", warn.level === "danger" ? "border-danger/50 bg-danger/10" : "border-warn/50 bg-warn/10")}>⚠️ {Math.round(warn.ratio * 100)}% من محفوظك مستحق للمراجعة — تُولَّد مهمة مراجعة تلقائيًا في «يومي». راجع اليوم قبل حفظ جديد.</div>}
    {due.length > 0 && <Card title={`مراجعات مستحقة (${due.length})`} action={<Button size="sm" variant="primary" onClick={() => quranActions.reviewAll(due.slice(0, 10))}>راجعت أول 10 ✓</Button>}><div className="flex flex-wrap gap-1">{due.slice(0, 60).map((pg) => <button key={pg} type="button" className="touch rounded-lg bg-warn/15 px-2 text-xs font-bold text-warn hover:bg-warn/30" onClick={() => quranActions.review(pg)} aria-label={`راجعت صفحة ${pg}`}>{pg}</button>)}{due.length > 60 && <span className="text-xs text-muted">+{due.length - 60}</span>}</div></Card>}
    <Card title="خريطة الحفظ" subtitle="اضغط صفحة لتسجيل حفظها، اضغط مطولًا/مرة أخرى لإلغائه" action={<Field label="فاصل المراجعة (يوم)"><Input type="number" className="w-24" value={q.reviewIntervalDays} onChange={(e) => update("quranMemorization", (x) => ({ ...x, reviewIntervalDays: Math.max(1, Number(e.target.value)) }))} /></Field>}>
      <div className="no-scrollbar mb-3 flex gap-1 overflow-x-auto">{Array.from({ length: JUZ_COUNT }, (_, i) => i + 1).map((j) => { const jp = pagesOfJuz(j); const done = jp.filter((x) => q.pages[String(x)]).length; return <Chip key={j} active={juz === j} onClick={() => setJuz(j)}>ج{j} <span className="opacity-70">{done}/{jp.length}</span></Chip>; })}</div>
      <div className="grid grid-cols-10 gap-1 sm:grid-cols-[repeat(21,minmax(0,1fr))]">{pages.map((pg) => { const st = q.pages[String(pg)]; const isDue = due.includes(pg); return <button key={pg} type="button" aria-pressed={!!st} aria-label={`صفحة ${pg}${st ? " محفوظة" : ""}${isDue ? " مستحقة" : ""}`} title={st ? `حُفظت ${st.memorizedAt} · مراجعات ${st.reviews}` : `صفحة ${pg}`} onClick={() => { if (!st) quranActions.memorize(pg); else if (isDue) quranActions.review(pg); else confirm(`إلغاء حفظ صفحة ${pg}؟`, () => quranActions.unmemorize(pg)); }} className={cx("touch aspect-square rounded-md text-[10px] font-bold transition", !st ? "bg-surface-2 text-muted hover:bg-line" : isDue ? "bg-warn text-black" : st.reviews >= 5 ? "bg-gold text-black" : "bg-ok text-white")}>{pg}</button>; })}</div>
      <div className="mt-2 flex flex-wrap gap-3 text-[10px] text-muted"><span>⬛ غير محفوظ</span><span>🟩 محفوظ</span><span>🟨 مستحق مراجعة (اضغط = راجعت)</span><span>🟡 متقن</span></div></Card>
    <Card title="تدبّر" subtitle="+8 XP"><div className="space-y-2"><Input placeholder="الآية / الموضع" value={tad.ref} onChange={(e) => setTad({ ...tad, ref: e.target.value })} /><Textarea placeholder="ما الذي وقف عنده قلبك؟" value={tad.text} onChange={(e) => setTad({ ...tad, text: e.target.value })} /><Button variant="primary" disabled={!tad.text.trim()} onClick={() => { quranActions.addTadabur(tad.ref, tad.text.trim()); setTad({ ref: "", text: "" }); }}>حفظ التدبر</Button></div>{data.quranTadabur.length ? <ul className="mt-3 space-y-2">{[...data.quranTadabur].reverse().slice(0, 20).map((t) => <li key={t.id} className="rounded-xl bg-surface-2 p-3 text-sm"><div className="text-[10px] text-muted">{t.date} · {t.ref}</div>{t.text}</li>)}</ul> : <EmptyState icon="🌙" title="لا تدبرات بعد" />}</Card>{dialog}
  </div>);
}
