"use client";
import React, { useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useApp } from "@/stores/app-store";
import { bodyActions, financeActions } from "@/stores/actions";
import { GoalSettings, LIFTS, LiftId } from "@/types/app-data";
import { BODY_METRICS, bodyProgress, estimateBioAge, estimateBodyFat, latestValue, liftSeries, metricSeries, nearestBodyEntry, overallBodyProgress, personalRecords, photoGroups, resizeImage } from "@/calculations/body";
import { quranGoalProgress } from "@/calculations/quran";
import { formatShort, todayISO } from "@/core/date";
import { Button, Card, Chip, Disclaimer, EmptyState, Field, Grid, Input, Modal, ProgressBar, ProgressRing, Select, StatCard, Tabs, useConfirm } from "@/components/ui";
import { LineSeries } from "@/components/charts";

const MILESTONES = [25, 50, 75, 100] as const;
const REWARD_IDEAS = ["وجبة مفضلة بلا حساب", "يوم راحة كامل", "كتاب جديد", "قطعة ملابس رياضية", "رحلة يوم واحد", "جلسة مساج", "أداة/جهاز صغير كنت تريده", "خروج مع صديق", "اشتراك دورة", "هدية لشخص تحبه"];

export default function GoalsPage() {
  const sp = useSearchParams(); const [tab, setTab] = useState<"goals" | "body" | "finance">((sp?.get("tab") as "goals" | "body" | "finance") || "goals");
  return (<div className="space-y-4 anim-fade-up"><Tabs value={tab} onChange={setTab} tabs={[{ id: "goals", label: "🎯 الأهداف" }, { id: "body", label: "🏋️ الجسم" }, { id: "finance", label: "💰 المال" }]} />{tab === "goals" && <GoalsTab />}{tab === "body" && <BodyTab initialView={sp?.get("view") ?? undefined} />}{tab === "finance" && <FinanceTab />}</div>);
}

function GoalsTab() {
  const data = useApp((s) => s.data); const update = useApp((s) => s.update); const gs = data.goalSettings; const set = (p: Partial<GoalSettings>) => update("goalSettings", (g) => ({ ...g, ...p }));
  const bp = bodyProgress(data.bodyEntries, gs); const quran = quranGoalProgress(data.quranMemorization, gs.quranMemGoalPages); const savings = data.savingsEntries.reduce((a, s) => a + s.amount, 0); const income = data.financeEntries.filter((f) => f.type === "income" && f.date.slice(0, 7) === todayISO().slice(0, 7)).reduce((a, f) => a + f.amount, 0);
  const goals: { key: string; label: string; percent: number; detail: string }[] = [
    { key: "quranMem", label: "حفظ القرآن", percent: quran, detail: `${Object.keys(data.quranMemorization.pages).length}/${gs.quranMemGoalPages} صفحة` },
    { key: "savings", label: "الادخار", percent: gs.savingsGoal ? Math.min(100, Math.round((savings / gs.savingsGoal) * 100)) : 0, detail: `${savings}/${gs.savingsGoal}` },
    { key: "income", label: "الدخل الشهري", percent: gs.incomeGoal ? Math.min(100, Math.round((income / gs.incomeGoal) * 100)) : 0, detail: `${income}/${gs.incomeGoal}` },
    ...bp.filter((m) => m.goal != null).map((m) => ({ key: m.key, label: m.label, percent: m.percent, detail: `${m.current ?? "—"} → ${m.goal} ${m.unit}` })),
  ];
  const num = (k: keyof GoalSettings, label: string, step = 1) => <Field key={k} label={label}><Input type="number" inputMode="decimal" step={step} value={(gs[k] as number | undefined) ?? ""} onChange={(e) => set({ [k]: e.target.value === "" ? undefined : Number(e.target.value) } as Partial<GoalSettings>)} /></Field>;
  return (<div className="space-y-3">
    <Card title="لوحة الأهداف" subtitle="كل هدف مرتبط ببيانات حقيقية"><div className="grid gap-2 md:grid-cols-2">{goals.map((g) => <div key={g.key} className="rounded-2xl border p-3"><div className="flex items-center justify-between text-sm"><b>{g.label}</b><span className="text-xs text-muted">{g.detail}</span></div><ProgressBar value={g.percent} className="my-2" color={g.percent >= 100 ? "var(--gold)" : "var(--accent)"} label={g.label} /><div className="flex gap-1">{MILESTONES.map((m) => { const id = `${g.key}:${m}`; const reached = g.percent >= m; const claimed = gs.rewardsClaimed.includes(id); const reward = gs.rewards[g.key]?.[String(m) as "25"]; return <button key={m} type="button" title={reward || "حدد مكافأة"} onClick={() => { if (reached && !claimed && reward) { set({ rewardsClaimed: [...gs.rewardsClaimed, id] }); useApp.getState().toast(`🎁 مكافأة مستحقة: ${reward}`, "ok"); } }} className={`flex-1 rounded-lg px-1 py-1 text-[10px] font-bold ${claimed ? "bg-gold text-black" : reached ? "anim-gold bg-gold-soft text-gold" : "bg-surface-2 text-muted"}`}>{m}%{reward ? " 🎁" : ""}</button>; })}</div></div>)}</div></Card>
    <Card title="المكافآت الذكية" subtitle="حدد مكافأة لكل معلم (25/50/75/100%) — تُقترح أفكار تلقائيًا"><div className="space-y-2">{goals.map((g) => <details key={g.key} className="rounded-xl border p-2"><summary className="cursor-pointer text-sm font-bold">{g.label}</summary><div className="mt-2 grid gap-2 sm:grid-cols-2">{MILESTONES.map((m) => <Field key={m} label={`${m}%`}><div className="flex gap-1"><Input value={gs.rewards[g.key]?.[String(m) as "25"] ?? ""} onChange={(e) => set({ rewards: { ...gs.rewards, [g.key]: { ...(gs.rewards[g.key] ?? {}), [m]: e.target.value } } })} placeholder="مكافأة…" /><Button size="sm" aria-label="اقتراح" onClick={() => set({ rewards: { ...gs.rewards, [g.key]: { ...(gs.rewards[g.key] ?? {}), [m]: REWARD_IDEAS[(m / 25 + g.key.length) % REWARD_IDEAS.length] } } })}>🎲</Button></div></Field>)}</div></details>)}</div></Card>
    <Card title="ضبط الأهداف"><div className="grid gap-3 sm:grid-cols-2 md:grid-cols-3">{num("weightGoal", "الوزن المستهدف (كجم)", 0.5)}{num("waistGoal", "الخصر (سم)")}{num("chestGoal", "الصدر (سم)")}{num("armGoal", "الذراع (سم)")}{num("thighGoal", "الفخذ (سم)")}{num("bodyFatGoal", "دهون الجسم %")}{num("vo2maxGoal", "VO₂ Max")}{num("rhrGoal", "نبض الراحة")}{num("quranMemGoalPages", "هدف الحفظ (صفحات)")}{num("quranReadGoalPages", "هدف القراءة (صفحات)")}{num("incomeGoal", "هدف الدخل الشهري")}{num("savingsGoal", "هدف الادخار")}{num("calorieTarget", "السعرات اليومية")}{num("proteinTarget", "بروتين (جم)")}{num("carbTarget", "كارب (جم)")}{num("fatTarget", "دهون (جم)")}</div></Card>
  </div>);
}

function BodyTab({ initialView }: { initialView?: string }) {
  const data = useApp((s) => s.data); const update = useApp((s) => s.update); const view = (initialView as "summary" | "record" | "photos" | "charts" | "all") || (data.uiPrefs.bodyView as "summary") || "summary";
  const setView = (v: string) => update("uiPrefs", (u) => ({ ...u, bodyView: v }));
  const show = (v: string) => view === v || view === "all";
  return (<div className="space-y-3"><Tabs value={view} onChange={setView} tabs={[{ id: "summary", label: "ملخص" }, { id: "record", label: "تسجيل" }, { id: "photos", label: "صور" }, { id: "charts", label: "رسوم" }, { id: "all", label: "الكل" }]} />{show("summary") && <BodySummary />}{show("record") && <BodyRecord />}{show("photos") && <BodyPhotos />}{show("charts") && <BodyCharts />}</div>);
}
function BodySummary() {
  const data = useApp((s) => s.data); const p = data.bodyProfile; const e = data.bodyEntries;
  const bp = bodyProgress(e, data.goalSettings); const overall = overallBodyProgress(bp); const bf = estimateBodyFat(p, latestValue(e, "waist"), latestValue(e, "neck")); const bio = estimateBioAge(p, latestValue(e, "vo2max"), latestValue(e, "rhr"), bf); const prs = personalRecords(e);
  return (<div className="space-y-3"><div className="card flex items-center gap-4 p-4"><ProgressRing value={overall} size={96} color="var(--gold)" label="التقدم العام للجسم" /><div className="flex-1"><div className="text-sm font-extrabold">التقدم العام نحو أهداف الجسم</div><div className="text-xs text-muted">متوسط تقدم القياسات التي لها هدف</div><Grid className="mt-2"><StatCard label="دهون تقديرية" value={bf != null ? `${bf}%` : "—"} hint="US Navy" /><StatCard label="عمر بيولوجي تقديري" value={bio ?? "—"} hint={`عمرك ${new Date().getFullYear() - p.birthYear}`} /></Grid></div></div>
    <Disclaimer>تقديرات الدهون والعمر البيولوجي إرشادية وليست تشخيصًا طبيًا.</Disclaimer>
    <Grid cols={4}>{bp.map((m) => <StatCard key={m.key} label={m.label} value={m.current != null ? `${m.current}${m.unit ? " " + m.unit : ""}` : "—"} hint={m.goal != null ? `هدف ${m.goal} · ${m.percent}%` : m.first != null ? `بداية ${m.first}` : "لا بيانات"} />)}</Grid>
    <Card title="أرقامك القياسية (PRs)"><div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3">{LIFTS.map((l) => <div key={l.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-2 text-sm"><span>{l.label}</span>{prs[l.id] ? <b className="text-gold">{prs[l.id]!.weight} كجم × {prs[l.id]!.reps}</b> : <span className="text-xs text-muted">—</span>}</div>)}</div></Card></div>);
}
function BodyRecord() {
  const data = useApp((s) => s.data); const update = useApp((s) => s.update); const { confirm, dialog } = useConfirm();
  const [f, setF] = useState<Record<string, string>>({ date: todayISO() }); const [lifts, setLifts] = useState<Partial<Record<LiftId, { weight: string; reps: string }>>>({});
  const save = () => { const e: Record<string, unknown> = { date: f.date }; for (const m of BODY_METRICS) if (f[m.key]) e[m.key] = Number(f[m.key]); const L: Partial<Record<LiftId, { weight: number; reps: number }>> = {}; for (const [k, v] of Object.entries(lifts)) if (v?.weight) L[k as LiftId] = { weight: Number(v.weight), reps: Number(v.reps || 0) }; if (Object.keys(L).length) e.lifts = L; bodyActions.record(e as Parameters<typeof bodyActions.record>[0]); setF({ date: todayISO() }); setLifts({}); };
  return (<div className="space-y-3"><Card title="تسجيل قياسات" subtitle="+5 XP لكل يوم تسجيل"><div className="grid gap-3 sm:grid-cols-3"><Field label="التاريخ"><Input type="date" value={f.date} onChange={(e) => setF({ ...f, date: e.target.value })} /></Field>{BODY_METRICS.map((m) => <Field key={m.key} label={`${m.label} ${m.unit ? `(${m.unit})` : ""}`}><Input type="number" inputMode="decimal" step="0.1" value={f[m.key] ?? ""} onChange={(e) => setF({ ...f, [m.key]: e.target.value })} /></Field>)}</div>
    <div className="mt-3 text-xs font-bold text-muted">تمارين القوة (كجم × تكرار)</div><div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3">{LIFTS.map((l) => <div key={l.id} className="rounded-xl border p-2"><div className="mb-1 text-xs font-bold">{l.label}</div><div className="flex gap-1"><Input type="number" inputMode="decimal" placeholder="كجم" value={lifts[l.id]?.weight ?? ""} onChange={(e) => setLifts({ ...lifts, [l.id]: { weight: e.target.value, reps: lifts[l.id]?.reps ?? "" } })} /><Input type="number" inputMode="numeric" placeholder="تكرار" value={lifts[l.id]?.reps ?? ""} onChange={(e) => setLifts({ ...lifts, [l.id]: { weight: lifts[l.id]?.weight ?? "", reps: e.target.value } })} /></div></div>)}</div>
    <Button variant="primary" className="mt-3" onClick={save}>حفظ القياسات</Button></Card>
    <Card title="الملف الجسدي" subtitle="يُستخدم في BMR والدهون والعمر البيولوجي"><div className="grid gap-3 sm:grid-cols-4"><Field label="الطول (سم)"><Input type="number" value={data.bodyProfile.heightCm} onChange={(e) => update("bodyProfile", (b) => ({ ...b, heightCm: Number(e.target.value) }))} /></Field><Field label="سنة الميلاد"><Input type="number" value={data.bodyProfile.birthYear} onChange={(e) => update("bodyProfile", (b) => ({ ...b, birthYear: Number(e.target.value) }))} /></Field><Field label="الجنس"><Select value={data.bodyProfile.sex} onChange={(e) => update("bodyProfile", (b) => ({ ...b, sex: e.target.value as "male" | "female" }))}><option value="male">ذكر</option><option value="female">أنثى</option></Select></Field><Field label="معامل النشاط"><Select value={data.bodyProfile.activity} onChange={(e) => update("bodyProfile", (b) => ({ ...b, activity: Number(e.target.value) }))}><option value={1.2}>خامل 1.2</option><option value={1.375}>خفيف 1.375</option><option value={1.55}>متوسط 1.55</option><option value={1.725}>عالي 1.725</option></Select></Field></div></Card>
    <Card title="السجل"><div className="max-h-72 space-y-1 overflow-y-auto text-xs">{[...data.bodyEntries].sort((a, b) => b.date.localeCompare(a.date)).map((e) => <div key={e.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-2"><span><b>{e.date}</b> · {BODY_METRICS.filter((m) => e[m.key] != null).map((m) => `${m.label} ${e[m.key]}`).join(" · ")}{e.lifts && ` · ${Object.keys(e.lifts).length} تمارين`}</span><button type="button" aria-label="حذف" onClick={() => confirm("حذف السجل؟", () => bodyActions.remove(e.id))}>🗑</button></div>)}{!data.bodyEntries.length && <EmptyState icon="📏" title="لا قياسات بعد" />}</div></Card>{dialog}</div>);
}
function BodyPhotos() {
  const data = useApp((s) => s.data); const fileRef = useRef<HTMLInputElement>(null); const [meta, setMeta] = useState({ date: todayISO(), angle: "front" as "front" | "side" | "back", category: "تقدم", group: "" }); const [compare, setCompare] = useState<string[]>([]); const { confirm, dialog } = useConfirm();
  const groups = photoGroups(data.photos); const onFile = async (files: FileList | null) => { if (!files) return; for (const f of Array.from(files)) { const dataUrl = await resizeImage(f); bodyActions.addPhoto({ ...meta, group: meta.group || meta.date, dataUrl }); } };
  const cmp = compare.map((id) => data.photos.find((p) => p.id === id)).filter(Boolean);
  return (<div className="space-y-3"><Card title="إضافة صور" subtitle="تُضغط تلقائيًا · تُحفظ محليًا (لا تُرفع سحابيًا افتراضيًا)"><div className="grid gap-2 sm:grid-cols-4"><Field label="التاريخ"><Input type="date" value={meta.date} onChange={(e) => setMeta({ ...meta, date: e.target.value })} /></Field><Field label="الزاوية"><Select value={meta.angle} onChange={(e) => setMeta({ ...meta, angle: e.target.value as "front" })}><option value="front">أمام</option><option value="side">جانب</option><option value="back">خلف</option></Select></Field><Field label="التصنيف"><Input value={meta.category} onChange={(e) => setMeta({ ...meta, category: e.target.value })} /></Field><Field label="المجموعة" hint="فارغ = التاريخ"><Input value={meta.group} onChange={(e) => setMeta({ ...meta, group: e.target.value })} /></Field></div><input ref={fileRef} type="file" accept="image/*" multiple className="hidden" onChange={(e) => onFile(e.target.files)} /><Button variant="primary" className="mt-2" onClick={() => fileRef.current?.click()}>📷 اختيار صور</Button></Card>
    {cmp.length === 2 && <Card title="مقارنة" action={<Button size="sm" onClick={() => setCompare([])}>إغلاق</Button>}><div className="grid grid-cols-2 gap-2">{cmp.map((p) => { const n = nearestBodyEntry(data.bodyEntries, p!.date); return <div key={p!.id}><img src={p!.dataUrl} alt={`${p!.angle} ${p!.date}`} className="w-full rounded-xl" /><div className="mt-1 text-xs text-muted">{p!.date}{n ? ` · وزن ${n.weight ?? "—"} · خصر ${n.waist ?? "—"}` : ""}</div></div>; })}</div></Card>}
    {Object.keys(groups).length === 0 && <EmptyState icon="🖼️" title="لا صور بعد" description="التقط صور أمام/جانب/خلف بشكل دوري لتتبع التغير بصريًا." />}
    {Object.entries(groups).sort((a, b) => b[0].localeCompare(a[0])).map(([g, ps]) => { const n = nearestBodyEntry(data.bodyEntries, ps[0].date); return <Card key={g} title={g} subtitle={n ? `أقرب قياس: ${n.date} · وزن ${n.weight ?? "—"} كجم · خصر ${n.waist ?? "—"}` : "لا قياس قريب"}><div className="grid grid-cols-3 gap-2">{ps.map((p) => <figure key={p.id} className={`relative overflow-hidden rounded-xl border ${compare.includes(p.id) ? "ring-2 ring-accent" : ""}`}><img src={p.dataUrl} alt={`${p.angle} ${p.date}`} className="aspect-[3/4] w-full object-cover" /><figcaption className="flex items-center justify-between bg-surface-2 px-2 py-1 text-[10px]"><span>{{ front: "أمام", side: "جانب", back: "خلف" }[p.angle]} · {p.category}</span><span className="flex gap-1"><button type="button" onClick={() => setCompare(compare.includes(p.id) ? compare.filter((x) => x !== p.id) : [...compare.slice(-1), p.id])} aria-label="مقارنة">⇄</button><button type="button" onClick={() => confirm("حذف الصورة؟", () => bodyActions.removePhoto(p.id))} aria-label="حذف">🗑</button></span></figcaption></figure>)}</div></Card>; })}{dialog}</div>);
}
function BodyCharts() {
  const data = useApp((s) => s.data); const [lift, setLift] = useState<LiftId>("bench"); const [metric, setMetric] = useState<string>("weight");
  const ms = useMemo(() => metricSeries(data.bodyEntries, metric as "weight").map((x) => ({ date: formatShort(x.date), value: x.value })), [data.bodyEntries, metric]);
  const ls = useMemo(() => liftSeries(data.bodyEntries, lift).map((x) => ({ date: formatShort(x.date), weight: x.weight, reps: x.reps })), [data.bodyEntries, lift]);
  return (<div className="space-y-3"><div className="flex flex-wrap gap-1.5">{BODY_METRICS.map((m) => <Chip key={m.key} active={metric === m.key} onClick={() => setMetric(m.key)}>{m.label}</Chip>)}</div><LineSeries title={`تطور ${BODY_METRICS.find((m) => m.key === metric)?.label}`} data={ms} x="date" series={[{ key: "value", color: "var(--accent)", name: BODY_METRICS.find((m) => m.key === metric)?.label }]} area /><div className="flex flex-wrap gap-1.5">{LIFTS.map((l) => <Chip key={l.id} active={lift === l.id} onClick={() => setLift(l.id)}>{l.label}</Chip>)}</div><LineSeries title={`قوة: ${LIFTS.find((l) => l.id === lift)?.label}`} data={ls} x="date" series={[{ key: "weight", color: "var(--gold)", name: "كجم" }, { key: "reps", color: "var(--accent)", name: "تكرار" }]} /></div>);
}
function FinanceTab() {
  const data = useApp((s) => s.data); const gs = data.goalSettings; const { confirm, dialog } = useConfirm(); const [f, setF] = useState({ date: todayISO(), type: "income" as "income" | "expense", amount: "", category: "", note: "" }); const [sv, setSv] = useState({ amount: "", note: "" });
  const month = todayISO().slice(0, 7); const mIn = data.financeEntries.filter((x) => x.type === "income" && x.date.startsWith(month)).reduce((a, x) => a + x.amount, 0); const mOut = data.financeEntries.filter((x) => x.type === "expense" && x.date.startsWith(month)).reduce((a, x) => a + x.amount, 0); const savings = data.savingsEntries.reduce((a, x) => a + x.amount, 0);
  return (<div className="space-y-3"><Grid cols={4}><StatCard label="دخل الشهر" value={mIn} hint={gs.incomeGoal ? `هدف ${gs.incomeGoal}` : ""} tone="ok" icon="💵" /><StatCard label="مصروف الشهر" value={mOut} tone="danger" icon="🧾" /><StatCard label="صافي الشهر" value={mIn - mOut} icon="⚖️" /><StatCard label="إجمالي الادخار" value={savings} hint={gs.savingsGoal ? `${Math.round((savings / gs.savingsGoal) * 100)}% من ${gs.savingsGoal}` : ""} tone="gold" icon="🏦" /></Grid>
    <Card title="تسجيل حركة"><div className="grid gap-2 sm:grid-cols-5"><Input type="date" value={f.date} onChange={(e) => setF({ ...f, date: e.target.value })} /><Select value={f.type} onChange={(e) => setF({ ...f, type: e.target.value as "income" })}><option value="income">دخل</option><option value="expense">مصروف</option></Select><Input type="number" inputMode="decimal" placeholder="المبلغ" value={f.amount} onChange={(e) => setF({ ...f, amount: e.target.value })} /><Input placeholder="التصنيف" value={f.category} onChange={(e) => setF({ ...f, category: e.target.value })} /><Button variant="primary" disabled={!f.amount} onClick={() => { financeActions.add({ ...f, amount: Number(f.amount) }); setF({ ...f, amount: "", note: "" }); }}>إضافة</Button></div></Card>
    <Card title="ادخار" subtitle="+5 XP لكل إيداع"><div className="grid gap-2 sm:grid-cols-3"><Input type="number" inputMode="decimal" placeholder="المبلغ" value={sv.amount} onChange={(e) => setSv({ ...sv, amount: e.target.value })} /><Input placeholder="ملاحظة" value={sv.note} onChange={(e) => setSv({ ...sv, note: e.target.value })} /><Button variant="gold" disabled={!sv.amount} onClick={() => { financeActions.addSavings(todayISO(), Number(sv.amount), sv.note); setSv({ amount: "", note: "" }); }}>إيداع</Button></div></Card>
    <Card title="السجل"><div className="max-h-80 space-y-1 overflow-y-auto text-sm">{[...data.financeEntries].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 100).map((x) => <div key={x.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-2"><span><span className="text-xs text-muted">{x.date}</span> · {x.category || (x.type === "income" ? "دخل" : "مصروف")}</span><span className="flex items-center gap-2"><b className={x.type === "income" ? "text-ok" : "text-danger"}>{x.type === "income" ? "+" : "−"}{x.amount}</b><button type="button" aria-label="حذف" onClick={() => confirm("حذف الحركة؟", () => financeActions.remove(x.id))}>🗑</button></span></div>)}{data.savingsEntries.map((x) => <div key={x.id} className="flex items-center justify-between rounded-xl bg-gold-soft px-3 py-2"><span><span className="text-xs text-muted">{x.date}</span> · ادخار {x.note}</span><span className="flex items-center gap-2"><b className="text-gold">{x.amount}</b><button type="button" aria-label="حذف" onClick={() => confirm("حذف الإيداع؟", () => financeActions.removeSavings(x.id))}>🗑</button></span></div>)}</div></Card>{dialog}</div>);
}
