"use client";
import React, { useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useApp, localRepo } from "@/stores/app-store";
import { habitActions } from "@/stores/actions";
import { AREAS, AreaId, Habit, ReviewQuestion } from "@/types/app-data";
import { METRICS } from "@/calculations/metrics";
import { CURRENT_SCHEMA_VERSION } from "@/migrations";
import { WEEKDAY_SHORT_AR, uid, nowISO } from "@/core/date";
import { Button, Card, Chip, Field, Grid, Input, Modal, Select, Tabs, Textarea, Toggle, cx, useConfirm } from "@/components/ui";

type SectionId = "profile" | "goals" | "areas" | "habits" | "daily" | "bonuses" | "nutrition" | "dhikr" | "recovery" | "triggers" | "rituals" | "rescue" | "reasons" | "letter" | "weekly" | "monthly" | "questions" | "training" | "books" | "courses" | "ai" | "notifications" | "appearance" | "data" | "cloud" | "pwa" | "advanced";
const SECTIONS: { id: SectionId; label: string; icon: string; group: string }[] = [
  { id: "profile", label: "الملف الشخصي", icon: "👤", group: "عام" }, { id: "appearance", label: "المظهر", icon: "🎨", group: "عام" }, { id: "notifications", label: "التنبيهات", icon: "🔔", group: "عام" }, { id: "pwa", label: "التطبيق (PWA)", icon: "📱", group: "عام" },
  { id: "goals", label: "الأهداف", icon: "🎯", group: "اللعبة" }, { id: "areas", label: "محاور الحياة", icon: "⚖️", group: "اللعبة" }, { id: "habits", label: "العادات", icon: "🔁", group: "اللعبة" }, { id: "daily", label: "المهام اليومية", icon: "☀️", group: "اللعبة" }, { id: "bonuses", label: "البونصات والعقوبات", icon: "⚡", group: "اللعبة" },
  { id: "nutrition", label: "التغذية", icon: "🍽️", group: "الجسد والدين" }, { id: "dhikr", label: "الأذكار", icon: "📿", group: "الجسد والدين" }, { id: "training", label: "التدريب", icon: "🧭", group: "الجسد والدين" },
  { id: "recovery", label: "التعافي", icon: "🌱", group: "التعافي" }, { id: "triggers", label: "المحفزات", icon: "⚠️", group: "التعافي" }, { id: "rituals", label: "الطقوس", icon: "🕯️", group: "التعافي" }, { id: "rescue", label: "بروتوكول الإنقاذ", icon: "🆘", group: "التعافي" }, { id: "reasons", label: "الأسباب", icon: "✦", group: "التعافي" }, { id: "letter", label: "الرسالة الشخصية", icon: "✉️", group: "التعافي" },
  { id: "weekly", label: "التخطيط الأسبوعي", icon: "📅", group: "التخطيط" }, { id: "monthly", label: "التخطيط الشهري", icon: "🗓️", group: "التخطيط" }, { id: "questions", label: "أسئلة المراجعة", icon: "❓", group: "التخطيط" },
  { id: "books", label: "الكتب", icon: "📚", group: "المكتبة" }, { id: "courses", label: "الدورات", icon: "🎓", group: "المكتبة" }, { id: "ai", label: "الذكاء الاصطناعي", icon: "🤖", group: "المكتبة" },
  { id: "data", label: "البيانات والنسخ", icon: "💾", group: "النظام" }, { id: "cloud", label: "المزامنة السحابية", icon: "☁️", group: "النظام" }, { id: "advanced", label: "متقدم", icon: "🧪", group: "النظام" },
];

export default function SettingsPage() {
  const sp = useSearchParams(); const [sec, setSec] = useState<SectionId | null>((sp?.get("section") as SectionId) || null);
  const groups = Array.from(new Set(SECTIONS.map((s) => s.group)));
  if (!sec) return (<div className="space-y-4 anim-fade-up"><h1 className="text-xl font-black">مركز الإعدادات</h1>{groups.map((g) => <div key={g}><div className="mb-1 text-xs font-bold text-muted">{g}</div><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{SECTIONS.filter((s) => s.group === g).map((s) => <button key={s.id} type="button" onClick={() => setSec(s.id)} className="card touch flex items-center gap-2 p-3 text-start text-sm font-bold hover:border-accent/50"><span className="text-lg" aria-hidden>{s.icon}</span>{s.label}</button>)}</div></div>)}</div>);
  const meta = SECTIONS.find((s) => s.id === sec)!;
  return (<div className="space-y-4 anim-fade-up"><div className="flex items-center gap-2"><Button size="sm" onClick={() => setSec(null)} aria-label="رجوع">‹ الإعدادات</Button><h1 className="text-lg font-black">{meta.icon} {meta.label}</h1></div><SectionBody id={sec} /></div>);
}

function ListEditor<T extends { id: string }>({ items, render, onAdd, onRemove, placeholder, addLabel = "+ إضافة" }: { items: T[]; render: (x: T) => React.ReactNode; onAdd: (text: string) => void; onRemove: (id: string) => void; placeholder: string; addLabel?: string }) {
  const [t, setT] = useState("");
  return (<div className="space-y-2"><ul className="space-y-1">{items.map((x) => <li key={x.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-2 text-sm"><span className="flex-1">{render(x)}</span><button type="button" aria-label="حذف" onClick={() => onRemove(x.id)}>✕</button></li>)}</ul><div className="flex gap-2"><Input value={t} onChange={(e) => setT(e.target.value)} placeholder={placeholder} onKeyDown={(e) => { if (e.key === "Enter" && t.trim()) { onAdd(t.trim()); setT(""); } }} /><Button onClick={() => { if (t.trim()) { onAdd(t.trim()); setT(""); } }}>{addLabel}</Button></div></div>);
}
function QuestionsEditor({ k, title }: { k: "dailyReviewQuestions" | "weeklyReviewQuestions" | "monthlyReviewQuestions" | "morningRecoveryQuestions" | "relapseQuestions"; title: string }) {
  const qs = useApp((s) => s.data[k]); const update = useApp((s) => s.update);
  return <Card title={title}><ListEditor<ReviewQuestion> items={qs} render={(q) => q.text} onAdd={(text) => update(k, (x) => [...x, { id: uid("q"), text }])} onRemove={(id) => update(k, (x) => x.filter((q) => q.id !== id))} placeholder="سؤال جديد…" /></Card>;
}

function SectionBody({ id }: { id: SectionId }) {
  const data = useApp((s) => s.data); const update = useApp((s) => s.update); const toast = useApp((s) => s.toast);
  switch (id) {
    case "profile": return <Card><Grid><Field label="الاسم"><Input value={data.bodyProfile.name ?? ""} onChange={(e) => update("bodyProfile", (b) => ({ ...b, name: e.target.value }))} /></Field><Field label="سنة الميلاد"><Input type="number" value={data.bodyProfile.birthYear} onChange={(e) => update("bodyProfile", (b) => ({ ...b, birthYear: Number(e.target.value) }))} /></Field><Field label="الطول (سم)"><Input type="number" value={data.bodyProfile.heightCm} onChange={(e) => update("bodyProfile", (b) => ({ ...b, heightCm: Number(e.target.value) }))} /></Field><Field label="الجنس"><Select value={data.bodyProfile.sex} onChange={(e) => update("bodyProfile", (b) => ({ ...b, sex: e.target.value as "male" }))}><option value="male">ذكر</option><option value="female">أنثى</option></Select></Field></Grid></Card>;
    case "appearance": return <Card title="السمة"><div className="flex gap-2">{(["dark", "light", "system"] as const).map((t) => <Chip key={t} active={data.uiPrefs.theme === t} onClick={() => update("uiPrefs", (u) => ({ ...u, theme: t }))}>{{ dark: "🌙 داكن", light: "☀️ فاتح", system: "🖥️ النظام" }[t]}</Chip>)}</div><div className="mt-3 flex items-center justify-between"><span className="text-sm">وضع مضغوط</span><Toggle checked={data.uiPrefs.compact} onChange={(v) => update("uiPrefs", (u) => ({ ...u, compact: v }))} label="مضغوط" /></div></Card>;
    case "notifications": return <Card title="التنبيهات"><div className="flex items-center justify-between"><div><div className="text-sm font-bold">تنبيهات المتصفح</div><div className="text-xs text-muted">تذكير بالإغلاق اليومي وقراءة التعافي (تعمل عند فتح التطبيق)</div></div><Toggle checked={data.uiPrefs.notifications} onChange={async (v) => { if (v && "Notification" in window) { const p = await Notification.requestPermission(); if (p !== "granted") return toast("لم يُمنح الإذن", "warn"); } update("uiPrefs", (u) => ({ ...u, notifications: v })); }} label="تنبيهات" /></div><div className="mt-3 flex items-center justify-between"><span className="text-sm">تذكير التعافي اليومي</span><Toggle checked={data.recoveryCoachSettings.dailyReminder} onChange={(v) => update("recoveryCoachSettings", (r) => ({ ...r, dailyReminder: v }))} label="تذكير" /></div></Card>;
    case "pwa": return <PwaSection />;
    case "goals": return <Card title="الأهداف"><p className="text-sm text-muted">ضبط الأهداف موجود في صفحة الأهداف (ضبط الأهداف + المكافآت الذكية).</p><Button className="mt-2" onClick={() => (location.href = "/goals")}>فتح الأهداف</Button></Card>;
    case "areas": return <Card title="أوزان المحاور" subtitle="يؤثر على الدرجة الموزونة والرادار فقط"><div className="space-y-3">{AREAS.map((a) => <div key={a.id} className="flex items-center gap-3"><span className="w-24 text-sm">{a.emoji} {a.label}</span><input type="range" min={0} max={3} step={0.5} value={data.goalSettings.areaWeights[a.id]} aria-label={`وزن ${a.label}`} onChange={(e) => update("goalSettings", (g) => ({ ...g, areaWeights: { ...g.areaWeights, [a.id]: Number(e.target.value) } }))} className="flex-1" /><b className="w-8 tabular-nums">×{data.goalSettings.areaWeights[a.id]}</b></div>)}</div></Card>;
    case "habits": return <HabitsSection />;
    case "daily": return <div className="space-y-3"><QuestionsEditor k="dailyReviewQuestions" title="أسئلة المراجعة اليومية (Shutdown)" /><Card title="مكتبة الزلات"><ListEditor items={data.sinLibrary} render={(s) => s.name} onAdd={(name) => update("sinLibrary", (x) => [...x, { id: uid("s"), name }])} onRemove={(id) => update("sinLibrary", (x) => x.filter((s) => s.id !== id))} placeholder="زلة…" /></Card><Card title="بومودورو"><Grid cols={4}>{(["work", "short", "long", "rounds"] as const).map((k) => <Field key={k} label={{ work: "عمل (د)", short: "راحة قصيرة", long: "راحة طويلة", rounds: "جولات" }[k]}><Input type="number" value={data.pomodoroSettings[k]} onChange={(e) => update("pomodoroSettings", (p) => ({ ...p, [k]: Number(e.target.value) }))} /></Field>)}</Grid></Card></div>;
    case "bonuses": return <div className="space-y-3"><Card title="سلاسل العادات"><Grid cols={3}><Field label="بونص كل N يوم"><Input type="number" value={data.streakSettings.bonusEveryDays} onChange={(e) => update("streakSettings", (s) => ({ ...s, bonusEveryDays: Number(e.target.value) }))} /></Field><Field label="XP البونص"><Input type="number" value={data.streakSettings.bonusXp} onChange={(e) => update("streakSettings", (s) => ({ ...s, bonusXp: Number(e.target.value) }))} /></Field><Field label="عقوبة العادة الفائتة"><Input type="number" value={data.streakSettings.missPenalty} onChange={(e) => update("streakSettings", (s) => ({ ...s, missPenalty: Number(e.target.value) }))} /></Field></Grid></Card><Card title="مهام البونص"><BonusEditor /></Card></div>;
    case "nutrition": return <Card title="مكتبة الوجبات"><MealEditor /></Card>;
    case "dhikr": return <Card title="مكتبة الأذكار"><DhikrEditor /></Card>;
    case "training": return <Card title="مجالات التدريب"><ul className="space-y-1 text-sm">{data.trainingLog.areas.map((a) => <li key={a.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-2"><span><span className="inline-block h-3 w-3 rounded-full" style={{ background: a.color }} /> {a.name} · {AREAS.find((x) => x.id === a.lifeArea)?.label}</span>{a.custom && <button type="button" onClick={() => update("trainingLog", (l) => ({ ...l, areas: l.areas.filter((x) => x.id !== a.id) }))}>✕</button>}</li>)}</ul><p className="mt-2 text-xs text-muted">أضف مجالات جديدة من صفحة التدريب.</p></Card>;
    case "recovery": return <div className="space-y-3"><Card title="إعدادات المدرّب"><Grid><Field label="النبرة"><Select value={data.recoveryCoachSettings.tone} onChange={(e) => update("recoveryCoachSettings", (r) => ({ ...r, tone: e.target.value as "gentle" }))}><option value="gentle">لطيفة</option><option value="firm">حازمة</option></Select></Field><div className="flex items-center justify-between"><span className="text-sm">إظهار مؤشر الخطر</span><Toggle checked={data.recoveryCoachSettings.showRisk} onChange={(v) => update("recoveryCoachSettings", (r) => ({ ...r, showRisk: v }))} label="الخطر" /></div></Grid><Field label="بداية الرحلة" className="mt-3"><Input type="date" value={data.sobrietyStartAt?.slice(0, 10) ?? ""} onChange={(e) => update("sobrietyStartAt", () => (e.target.value ? new Date(e.target.value).toISOString() : null))} /></Field></Card><QuestionsEditor k="relapseQuestions" title="أسئلة ما بعد الانتكاس" /><QuestionsEditor k="morningRecoveryQuestions" title="أسئلة الصباح" /></div>;
    case "triggers": return <Card title="المحفزات"><ListEditor items={data.recoveryTriggers} render={(t) => t.name} onAdd={(name) => update("recoveryTriggers", (x) => [...x, { id: uid("t"), name }])} onRemove={(id) => update("recoveryTriggers", (x) => x.filter((t) => t.id !== id))} placeholder="محفز…" /></Card>;
    case "rituals": return <Card title="الطقوس"><ListEditor items={data.recoveryRituals} render={(r) => `${r.name} · ${{ morning: "صباح", evening: "مساء", any: "أي وقت" }[r.when]}`} onAdd={(name) => update("recoveryRituals", (x) => [...x, { id: uid("r"), name, when: "any" }])} onRemove={(id) => update("recoveryRituals", (x) => x.filter((r) => r.id !== id))} placeholder="طقس…" /></Card>;
    case "rescue": return <Card title="بروتوكول الإنقاذ"><Field label="رقم/جهة شخص الدعم"><Input value={data.rescueProtocol.supportContact} onChange={(e) => update("rescueProtocol", (r) => ({ ...r, supportContact: e.target.value, updatedAt: nowISO() }))} placeholder="+20…" /></Field><Field label="الخطوات (سطر لكل خطوة)" className="mt-3"><Textarea value={data.rescueProtocol.steps.join("\n")} onChange={(e) => update("rescueProtocol", (r) => ({ ...r, steps: e.target.value.split("\n"), updatedAt: nowISO() }))} /></Field></Card>;
    case "reasons": return <Card title="أسباب التعافي" subtitle="تظهر في SOS"><ListEditor items={data.recoveryReasons} render={(r) => r.text} onAdd={(text) => update("recoveryReasons", (x) => [...x, { id: uid("rs"), text }])} onRemove={(id) => update("recoveryReasons", (x) => x.filter((r) => r.id !== id))} placeholder="لماذا أتعافى؟" /></Card>;
    case "letter": return <Card title="رسالة لنفسك في اللحظة الصعبة" subtitle={data.recoveryLetter.updatedAt ? `آخر تحديث ${data.recoveryLetter.updatedAt.slice(0, 10)}` : ""}><Textarea className="min-h-[220px] leading-7" value={data.recoveryLetter.text} onChange={(e) => update("recoveryLetter", () => ({ text: e.target.value, updatedAt: nowISO() }))} placeholder="عزيزي أنا، عندما تقرأ هذا…" /></Card>;
    case "weekly": return <div className="space-y-3"><QuestionsEditor k="weeklyReviewQuestions" title="أسئلة المراجعة الأسبوعية" /><Card title="قوالب الأهداف الأسبوعية"><p className="text-xs text-muted">{data.weeklyGoalTemplates.length} قالب — تُدار من صفحة الأسبوع › الأهداف.</p></Card></div>;
    case "monthly": return <div className="space-y-3"><QuestionsEditor k="monthlyReviewQuestions" title="أسئلة المراجعة الشهرية" /><Card title="قوالب الأهداف الشهرية"><p className="text-xs text-muted">{data.monthlyGoalTemplates.length} قالب — تُدار من صفحة الشهر › الأهداف.</p></Card></div>;
    case "questions": return <div className="space-y-3"><QuestionsEditor k="dailyReviewQuestions" title="يومية" /><QuestionsEditor k="weeklyReviewQuestions" title="أسبوعية" /><QuestionsEditor k="monthlyReviewQuestions" title="شهرية" /><QuestionsEditor k="morningRecoveryQuestions" title="صباح التعافي" /><QuestionsEditor k="relapseQuestions" title="بعد الانتكاس" /></div>;
    case "books": return <Card title="القارئ"><Grid cols={3}><Field label="الوضع الافتراضي"><Select value={data.uiPrefs.reader.mode} onChange={(e) => update("uiPrefs", (u) => ({ ...u, reader: { ...u.reader, mode: e.target.value as "dark" } }))}><option value="light">فاتح</option><option value="dark">داكن</option><option value="sepia">سيبيا</option><option value="paper">ورقي</option></Select></Field><Field label="الملاءمة"><Select value={data.uiPrefs.reader.fit} onChange={(e) => update("uiPrefs", (u) => ({ ...u, reader: { ...u.reader, fit: e.target.value as "width" } }))}><option value="width">عرض</option><option value="page">صفحة</option><option value="none">تكبير يدوي</option></Select></Field></Grid><p className="mt-2 text-xs text-muted">ملفات PDF محفوظة في IndexedDB. عدد الكتب: {data.books.length} · تعليقات: {data.bookAnnotations.length}</p></Card>;
    case "courses": return <Card title="الدورات"><p className="text-sm text-muted">{data.courses.length} دورة · {data.courses.reduce((a, c) => a + c.lessons.length, 0)} درس. استيراد CSV من صفحة المكتبة › الدورات.</p></Card>;
    case "ai": return <Card title="الذكاء الاصطناعي"><Grid cols={3}><Field label="المزود"><Select value={data.aiAssistantSettings.provider} onChange={(e) => update("aiAssistantSettings", (a) => ({ ...a, provider: e.target.value as "auto" }))}><option value="auto">تلقائي (سحابي إن وُجد مفتاح)</option><option value="local">المدرّب المحلي فقط</option></Select></Field><Field label="النموذج"><Input value={data.aiAssistantSettings.model} onChange={(e) => update("aiAssistantSettings", (a) => ({ ...a, model: e.target.value }))} /></Field><Field label="Temperature"><Input type="number" step={0.1} min={0} max={1} value={data.aiAssistantSettings.temperature} onChange={(e) => update("aiAssistantSettings", (a) => ({ ...a, temperature: Number(e.target.value) }))} /></Field></Grid><div className="mt-3 space-y-2">{(Object.keys(data.aiModeSettings) as (keyof typeof data.aiModeSettings)[]).map((m) => <div key={m} className="flex items-center justify-between text-sm"><span>{m}</span><Toggle checked={data.aiModeSettings[m].enabled} onChange={(v) => update("aiModeSettings", (s) => ({ ...s, [m]: { ...s[m], enabled: v } }))} label={m} /></div>)}</div><p className="mt-3 text-xs text-muted">المفتاح OPENAI_API_KEY يُقرأ على الخادم فقط ولا يصل للمتصفح. تصدير سجل المحادثات من قسم البيانات.</p></Card>;
    case "data": return <DataSection />;
    case "cloud": return <CloudSection />;
    case "advanced": return <Card title="متقدم"><ul className="space-y-1 text-sm"><li>Schema: v{CURRENT_SCHEMA_VERSION}</li><li>عدد أيام مسجلة: {Object.keys(data.entries).length}</li><li>أحداث XP: {data.xpLog.length}</li><li>مفاتيح legacy محفوظة: {Object.keys(data.legacy).length ? Object.keys(data.legacy).join("، ") : "—"}</li></ul><Button className="mt-3" variant="danger" onClick={() => update("uiPrefs", (u) => ({ ...u, onboarded: false }))}>إعادة شاشة الترحيب</Button></Card>;
  }
}
function HabitsSection() {
  const habits = useApp((s) => s.data.habits); const [edit, setEdit] = useState<Habit | null>(null); const { confirm, dialog } = useConfirm();
  const blank: Habit = { id: "", name: "", area: "mental", days: [0, 1, 2, 3, 4, 5, 6], optionalDays: [], enabled: true, custom: true, xp: 8 };
  const toggleDay = (h: Habit, d: number, kind: "days" | "optionalDays") => { const other = kind === "days" ? "optionalDays" : "days"; const has = h[kind].includes(d); return { ...h, [kind]: has ? h[kind].filter((x) => x !== d) : [...h[kind], d], [other]: h[other].filter((x) => x !== d) }; };
  return (<div className="space-y-2"><p className="text-xs text-muted">الأيام المجدولة = مطلوبة (فواتها يكسر السلسلة ويُخصم). الاختيارية = بونص. غير ذلك = يوم راحة لا يكسر السلسلة.</p>
    {habits.map((h, i) => <div key={h.id} className={cx("card flex items-center gap-2 p-3", !h.enabled && "opacity-60")}><Toggle checked={h.enabled} onChange={(v) => habitActions.edit(h.id, { enabled: v })} label={h.name} /><div className="min-w-0 flex-1"><div className="text-sm font-bold">{h.emoji} {h.name} <span className="text-[10px] text-muted">+{h.xp}</span></div><div className="text-[11px] text-muted">{AREAS.find((a) => a.id === h.area)?.label} · مطلوب: {h.days.map((d) => WEEKDAY_SHORT_AR[d]).join(" ")} {h.optionalDays.length ? `· اختياري: ${h.optionalDays.map((d) => WEEKDAY_SHORT_AR[d]).join(" ")}` : ""}{h.metric ? ` · مقياس: ${METRICS.find((m) => m.id === h.metric)?.label}` : ""}{h.quranMode ? ` · قرآن: ${h.quranMode === "new" ? "حفظ" : "مراجعة"}` : ""}</div></div><div className="flex gap-1"><Button size="sm" aria-label="أعلى" disabled={i === 0} onClick={() => habitActions.move(h.id, -1)}>↑</Button><Button size="sm" aria-label="أسفل" disabled={i === habits.length - 1} onClick={() => habitActions.move(h.id, 1)}>↓</Button><Button size="sm" onClick={() => setEdit(h)}>تعديل</Button>{h.custom && <Button size="sm" variant="ghost" onClick={() => confirm("حذف العادة؟", () => habitActions.remove(h.id))}>🗑</Button>}</div></div>)}
    <Button variant="primary" onClick={() => setEdit(blank)}>+ عادة مخصصة</Button>
    <Modal open={!!edit} onClose={() => setEdit(null)} title={edit?.id ? "تعديل عادة" : "عادة جديدة"} footer={<Button variant="primary" disabled={!edit?.name.trim()} onClick={() => { if (!edit) return; if (edit.id) habitActions.edit(edit.id, edit); else habitActions.add(edit); setEdit(null); }}>حفظ</Button>}>{edit && <div className="space-y-3"><Grid><Field label="الاسم"><Input value={edit.name} onChange={(e) => setEdit({ ...edit, name: e.target.value })} /></Field><Field label="رمز"><Input value={edit.emoji ?? ""} onChange={(e) => setEdit({ ...edit, emoji: e.target.value })} /></Field><Field label="XP"><Input type="number" value={edit.xp} onChange={(e) => setEdit({ ...edit, xp: Number(e.target.value) })} /></Field><Field label="المحور"><Select value={edit.area} onChange={(e) => setEdit({ ...edit, area: e.target.value as AreaId })}>{AREAS.map((a) => <option key={a.id} value={a.id}>{a.label}</option>)}</Select></Field></Grid>
      <Field label="الأيام المطلوبة"><div className="flex gap-1">{WEEKDAY_SHORT_AR.map((d, i) => <Chip key={i} active={edit.days.includes(i)} onClick={() => setEdit(toggleDay(edit, i, "days"))}>{d}</Chip>)}</div></Field><Field label="أيام اختيارية"><div className="flex gap-1">{WEEKDAY_SHORT_AR.map((d, i) => <Chip key={i} active={edit.optionalDays.includes(i)} onClick={() => setEdit(toggleDay(edit, i, "optionalDays"))}>{d}</Chip>)}</div></Field>
      <Grid><Field label="ربط بمقياس (يكتمل تلقائيًا)"><Select value={edit.metric ?? ""} onChange={(e) => setEdit({ ...edit, metric: e.target.value || undefined })}><option value="">— بدون —</option>{METRICS.map((m) => <option key={m.id} value={m.id}>{m.label}</option>)}</Select></Field><Field label="وضع القرآن"><Select value={edit.quranMode ?? ""} onChange={(e) => setEdit({ ...edit, quranMode: (e.target.value || undefined) as "new" | undefined })}><option value="">—</option><option value="new">حفظ جديد</option><option value="review">مراجعة</option></Select></Field></Grid></div>}</Modal>{dialog}</div>);
}
function BonusEditor() { const bq = useApp((s) => s.data.bonusQuests); const update = useApp((s) => s.update); const [f, setF] = useState({ title: "", xp: 5, area: "mental" as AreaId }); return (<div className="space-y-2">{bq.map((b) => <div key={b.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-2 text-sm"><span>{b.title} <span className="text-gold">+{b.xp}</span></span><span className="flex items-center gap-2"><Toggle checked={b.enabled} onChange={(v) => update("bonusQuests", (x) => x.map((y) => (y.id === b.id ? { ...y, enabled: v } : y)))} label={b.title} /><button type="button" onClick={() => update("bonusQuests", (x) => x.filter((y) => y.id !== b.id))}>✕</button></span></div>)}<div className="grid gap-2 sm:grid-cols-[2fr_1fr_1fr_auto]"><Input placeholder="مهمة بونص" value={f.title} onChange={(e) => setF({ ...f, title: e.target.value })} /><Input type="number" value={f.xp} onChange={(e) => setF({ ...f, xp: Number(e.target.value) })} /><Select value={f.area} onChange={(e) => setF({ ...f, area: e.target.value as AreaId })}>{AREAS.map((a) => <option key={a.id} value={a.id}>{a.label}</option>)}</Select><Button onClick={() => { if (f.title.trim()) { update("bonusQuests", (x) => [...x, { id: uid("bq"), ...f, enabled: true }]); setF({ ...f, title: "" }); } }}>+</Button></div></div>); }
function MealEditor() { const ml = useApp((s) => s.data.mealLibrary); const update = useApp((s) => s.update); const [f, setF] = useState({ name: "", kcal: 0, protein: 0, carbs: 0, fat: 0 }); return (<div className="space-y-2">{ml.map((m) => <div key={m.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-2 text-sm"><span>{m.name} <span className="text-xs text-muted">{m.kcal} kcal · P{m.protein} C{m.carbs} F{m.fat}</span></span><button type="button" onClick={() => update("mealLibrary", (x) => x.filter((y) => y.id !== m.id))}>✕</button></div>)}<div className="grid grid-cols-2 gap-2 sm:grid-cols-6"><Input className="col-span-2" placeholder="اسم الوجبة" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} />{(["kcal", "protein", "carbs", "fat"] as const).map((k) => <Input key={k} type="number" placeholder={k} value={f[k] || ""} onChange={(e) => setF({ ...f, [k]: Number(e.target.value) })} />)}</div><Button onClick={() => { if (f.name.trim()) { update("mealLibrary", (x) => [...x, { id: uid("m"), ...f }]); setF({ name: "", kcal: 0, protein: 0, carbs: 0, fat: 0 }); } }}>+ وجبة</Button></div>); }
function DhikrEditor() { const dl = useApp((s) => s.data.dhikrLibrary); const update = useApp((s) => s.update); const [f, setF] = useState({ text: "", target: 100, xp: 5 }); return (<div className="space-y-2">{dl.map((d) => <div key={d.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-2 text-sm"><span>{d.text} <span className="text-xs text-muted">هدف {d.target} · +{d.xp}</span></span><button type="button" onClick={() => update("dhikrLibrary", (x) => x.filter((y) => y.id !== d.id))}>✕</button></div>)}<div className="grid gap-2 sm:grid-cols-[2fr_1fr_1fr_auto]"><Input placeholder="الذكر" value={f.text} onChange={(e) => setF({ ...f, text: e.target.value })} /><Input type="number" value={f.target} onChange={(e) => setF({ ...f, target: Number(e.target.value) })} /><Input type="number" value={f.xp} onChange={(e) => setF({ ...f, xp: Number(e.target.value) })} /><Button onClick={() => { if (f.text.trim()) { update("dhikrLibrary", (x) => [...x, { id: uid("d"), ...f }]); setF({ ...f, text: "" }); } }}>+</Button></div></div>); }
function PwaSection() {
  const [installed] = useState(() => typeof window !== "undefined" && window.matchMedia("(display-mode: standalone)").matches); const [canInstall] = useState(() => typeof window !== "undefined" && !!(window as unknown as { __pwaPrompt?: unknown }).__pwaPrompt);
  return <Card title="التطبيق (PWA)"><ul className="space-y-1 text-sm"><li>الحالة: {installed ? "✅ مثبت" : "غير مثبت"}</li><li>يعمل بلا إنترنت: ✅ (البيانات محلية + الواجهة مخزنة)</li><li>المزامنة عند عودة الاتصال: ✅</li></ul>{!installed && <Button className="mt-3" variant="primary" disabled={!canInstall} onClick={async () => { const p = (window as unknown as { __pwaPrompt?: { prompt: () => Promise<void> } }).__pwaPrompt; await p?.prompt(); }}>{canInstall ? "تثبيت التطبيق" : "استخدم «إضافة إلى الشاشة الرئيسية» من قائمة المتصفح"}</Button>}</Card>;
}
function DataSection() {
  const data = useApp((s) => s.data); const exportAll = useApp((s) => s.exportAll); const restoreFrom = useApp((s) => s.restoreFrom); const resetAll = useApp((s) => s.resetAll); const toast = useApp((s) => s.toast); const fileRef = useRef<HTMLInputElement>(null); const [mode, setMode] = useState<"merge" | "replace">("merge"); const [snaps, setSnaps] = useState<{ id: string; at: number; label: string }[]>([]); const { confirm, dialog } = useConfirm(); const [result, setResult] = useState<string | null>(null);
  useEffect(() => { localRepo.listSnapshots().then(setSnaps); }, [result]);
  const dl = (name: string, content: string, type = "application/json") => { const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([content], { type })); a.download = name; a.click(); };
  const stamp = new Date().toISOString().slice(0, 10);
  const md = () => { const lines = [`# تقرير Me vs Me — ${stamp}`, "", `- XP إجمالي: ${data.xpLog.reduce((a, e) => a + e.amount, 0)}`, `- أيام مسجلة: ${Object.keys(data.entries).length}`, `- كتب: ${data.books.length} · دورات: ${data.courses.length}`, `- محفوظ القرآن: ${Object.keys(data.quranMemorization.pages).length} صفحة`, "", "## آخر 14 يومًا", ...Object.values(data.entries).sort((a, b) => b.date.localeCompare(a.date)).slice(0, 14).map((e) => `- ${e.date}: ${e.closed ? `مغلق ${e.score}%` : "مفتوح"} · مهام ${e.tasks.filter((t) => t.done).length}/${e.tasks.length}${e.note ? ` · ${e.note}` : ""}`), "", "## تأملات", ...data.reflections.slice(-20).map((r) => `- ${r.date}: ${r.text}`)]; dl(`mevsme-report-${stamp}.md`, lines.join("\n"), "text/markdown"); };
  return (<div className="space-y-3">
    <Card title="نسخة احتياطية كاملة" subtitle={`schema v${CURRENT_SCHEMA_VERSION} · تشمل كل المفاتيح (${Object.keys(data).length}) بما فيها الصور`}><div className="flex flex-wrap gap-2"><Button variant="primary" onClick={() => dl(`mevsme-backup-${stamp}.json`, exportAll())}>⬇️ تصدير JSON</Button><Button onClick={md}>📝 تقرير Markdown</Button><Button onClick={() => dl(`mevsme-library-${stamp}.json`, JSON.stringify({ books: data.books, courses: data.courses, annotations: data.bookAnnotations }, null, 2))}>📚 تصدير المكتبة</Button><Button onClick={() => dl(`mevsme-ai-${stamp}.json`, JSON.stringify({ chats: data.aiChatsByMode, memories: data.aiMemoriesByMode, skills: data.aiSkills }, null, 2))}>🤖 تصدير AI</Button><Button onClick={() => dl(`mevsme-annotations-${stamp}.json`, JSON.stringify(data.bookAnnotations, null, 2))}>🖍 تصدير التعليقات</Button></div></Card>
    <Card title="استعادة" subtitle="يقبل نسخ الإصدار القديم (مسطحة) والجديد — مع ترقية تلقائية وتحقق"><div className="mb-2 flex gap-2"><Chip active={mode === "merge"} onClick={() => setMode("merge")}>دمج آمن (موصى به)</Chip><Chip active={mode === "replace"} onClick={() => setMode("replace")}>استبدال</Chip></div><input ref={fileRef} type="file" accept="application/json,.json" className="hidden" onChange={async (e) => { const f = e.target.files?.[0]; if (!f) return; const text = await f.text(); confirm(mode === "replace" ? "استبدال كل البيانات الحالية؟ (تُحفظ نسخة تلقائية قبلها)" : "دمج النسخة مع بياناتك؟", async () => { const r = await restoreFrom(text, mode); setResult(r.message + (r.counts ? ` — ${Object.values(r.counts).reduce((a, b) => a + b, 0)} سجل` : "")); toast(r.message, r.ok ? "ok" : "error"); }, undefined, mode === "replace"); e.target.value = ""; }} /><Button onClick={() => fileRef.current?.click()}>⬆️ اختيار ملف</Button>{result && <p className="mt-2 text-xs">{result}</p>}</Card>
    <Card title="النسخ التلقائية (Snapshots)" subtitle="تُنشأ قبل كل استعادة/استيراد/إعادة تعيين">{snaps.length ? <ul className="space-y-1 text-sm">{snaps.map((s) => <li key={s.id} className="flex items-center justify-between rounded-xl bg-surface-2 px-3 py-2"><span>{s.label} · {new Date(s.at).toLocaleString("ar")}</span><Button size="sm" onClick={() => confirm("الرجوع إلى هذه النسخة؟ (استبدال)", async () => { const p = await localRepo.getSnapshot(s.id); if (p) { const r = await restoreFrom(JSON.stringify(p), "replace"); toast(r.message, r.ok ? "ok" : "error"); } })}>استرجاع</Button></li>)}</ul> : <p className="text-xs text-muted">لا نسخ بعد.</p>}</Card>
    <Card title="إعادة تعيين" tone="danger"><p className="mb-2 text-xs text-muted">يمسح كل البيانات المحلية (تُحفظ نسخة تلقائية أولًا). البيانات السحابية ستُستبدل عند المزامنة التالية.</p><Button variant="danger" onClick={() => confirm("إعادة تعيين كل شيء؟", () => resetAll(), "صدّر نسخة أولًا. لا يمكن التراجع إلا من النسخ التلقائية.")}>إعادة تعيين الكل</Button></Card>{dialog}
  </div>);
}
function CloudSection() {
  const account = useApp((s) => s.account); const sync = useApp((s) => s.sync); const syncNow = useApp((s) => s.syncNow); const linkAccount = useApp((s) => s.linkAccount); const toast = useApp((s) => s.toast); const [code, setCode] = useState(""); const [busy, setBusy] = useState(false);
  return (<div className="space-y-3"><Card title="الحالة"><ul className="space-y-1 text-sm"><li>الحالة: <b>{{ idle: "متزامن", syncing: "جارٍ…", offline: "غير متصل", disabled: "السحابة غير مُفعّلة (Firebase غير مُهيّأ)", error: `خطأ: ${sync.error ?? ""}` }[sync.state]}</b></li><li>تغييرات معلّقة: {sync.pending}</li><li>آخر مزامنة: {sync.lastSyncAt ? new Date(sync.lastSyncAt).toLocaleString("ar") : "—"}</li></ul><Button className="mt-2" onClick={() => syncNow()}>مزامنة الآن</Button><p className="mt-2 text-[11px] text-muted">Local-first: الكتابة محليًا أولًا، ثم طابور مزامنة، ثم دمج غير مدمّر (الأحدث يفوز لكل مفتاح، والمحلي له الأولوية عند وجود تغييرات معلّقة). الصور وملفات PDF لا تُرفع. التخزين السحابي: Firebase Firestore.</p></Card>
    <Card title="ربط الأجهزة" subtitle="انسخ رمز الحساب وأدخله على جهاز آخر"><div className="rounded-xl bg-surface-2 p-3 text-center font-mono text-xl font-black tracking-widest" dir="ltr">{account.code}</div><Button size="sm" className="mt-2" onClick={() => { navigator.clipboard?.writeText(account.code); toast("تم النسخ", "ok"); }}>نسخ الرمز</Button><div className="mt-4 flex gap-2"><Input value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="رمز جهاز آخر…" dir="ltr" /><Button variant="primary" disabled={busy || code.length < 6} onClick={async () => { setBusy(true); const ok = await linkAccount(code.trim()); setBusy(false); toast(ok ? "تم الربط والمزامنة" : "رمز غير موجود", ok ? "ok" : "error"); }}>ربط</Button></div><p className="mt-2 text-[11px] text-muted">الربط يدمج بيانات هذا الجهاز مع الحساب الآخر بدون حذف.</p></Card></div>);
}
