"use client";
import React, { useEffect, useState } from "react";
import { useApp } from "@/stores/app-store";
import { challengeActions } from "@/stores/actions";
import { AREAS, AreaId, Challenge, ChallengeType } from "@/types/app-data";
import { challengeState } from "@/calculations/challenges";
import { METRICS } from "@/calculations/metrics";
import { todayISO } from "@/core/date";
import { Button, Card, Chip, EmptyState, Field, Grid, Input, Modal, NumberInput, ProgressBar, Select, StatCard, Tabs, cx, useConfirm, AreaChip } from "@/components/ui";

const TYPES: { id: ChallengeType; label: string; desc: string; icon: string }[] = [
  { id: "daily", label: "تكرار يومي", desc: "حقق الهدف كل يوم طوال المدة. يوم واحد فائت = فشل.", icon: "🔁" },
  { id: "weekly", label: "هدف أسبوعي", desc: "حقق مجموعًا أسبوعيًا كل أسبوع من المدة.", icon: "📅" },
  { id: "boss", label: "Boss Battle", desc: "مجموع كبير خلال المدة. النصر عند بلوغه قبل النهاية.", icon: "👹" },
];
export default function ChallengesPage() {
  const data = useApp((s) => s.data); const [tab, setTab] = useState<"active" | "done">("active"); const [open, setOpen] = useState(false); const { confirm, dialog } = useConfirm();
  const [f, setF] = useState({ title: "", type: "daily" as ChallengeType, source: "manual", target: 1, durationDays: 30, dailyReward: 5, successReward: 100, failurePenalty: 30, area: "mental" as AreaId, startDate: todayISO() });
  useEffect(() => { challengeActions.refreshStatuses(); }, [data.entries, data.courses, data.trainingLog]);
  const list = data.challenges.filter((c) => (tab === "active" ? c.status === "active" : c.status !== "active"));
  const [manual, setManual] = useState<Record<string, number>>({});
  return (<div className="space-y-4 anim-fade-up">
    <Grid cols={4}><StatCard label="نشطة" value={data.challenges.filter((c) => c.status === "active").length} tone="accent" icon="⚔️" /><StatCard label="منتصرة" value={data.challenges.filter((c) => c.status === "success").length} tone="gold" icon="🏆" /><StatCard label="فاشلة" value={data.challenges.filter((c) => c.status === "failed").length} tone="danger" icon="💀" /><StatCard label="XP من التحديات" value={data.xpLog.filter((e) => e.source === "challenge").reduce((a, e) => a + e.amount, 0)} icon="⚡" /></Grid>
    <div className="flex items-center justify-between"><Tabs value={tab} onChange={setTab} tabs={[{ id: "active", label: "النشطة" }, { id: "done", label: "المنتهية" }]} /><Button variant="primary" onClick={() => setOpen(true)}>+ تحدٍ</Button></div>
    {list.length === 0 && <EmptyState icon="⚔️" title={tab === "active" ? "لا تحديات نشطة" : "لا تحديات منتهية"} description="التحدي يعطي XP يومي ومكافأة نصر وعقوبة فشل. التقدم يُحسب تلقائيًا من بياناتك أو من دورة." />}
    <div className="grid gap-3 md:grid-cols-2">{list.map((c) => { const st = challengeState(c, data); const t = TYPES.find((x) => x.id === c.type)!; const src = c.source === "manual" ? "يدوي" : c.source.startsWith("course:") ? `دورة: ${data.courses.find((x) => x.id === c.source.slice(7))?.title ?? "?"}` : METRICS.find((m) => m.id === c.source)?.label ?? c.source; return <Card key={c.id} className={cx("p-4", c.status === "success" && "border-gold/50", c.status === "failed" && "border-danger/40 opacity-80")}><div className="flex items-start justify-between gap-2"><div><div className="text-base font-black">{t.icon} {c.title}</div><div className="mt-0.5 flex flex-wrap gap-1 text-[11px] text-muted"><AreaChip id={c.area} small /><span className="rounded-full bg-surface-2 px-1.5">{t.label}</span><span className="rounded-full bg-surface-2 px-1.5">المصدر: {src}</span></div></div><span className={cx("rounded-full px-2 py-0.5 text-xs font-bold", c.status === "active" ? "bg-accent-soft text-accent" : c.status === "success" ? "bg-gold text-black" : "bg-danger/15 text-danger")}>{{ active: `${st.daysLeft} يوم متبقٍ`, success: "نصر", failed: "فشل" }[c.status]}</span></div>
      <ProgressBar value={st.percent} className="my-3" color={c.status === "success" ? "var(--gold)" : c.status === "failed" ? "var(--danger)" : "var(--accent)"} label={c.title} height={10} />
      <div className="grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-xl bg-surface-2 p-2"><b>{c.type === "boss" ? `${st.total}/${c.target}` : c.type === "daily" ? `${st.successDays}/${c.durationDays}` : `${st.weeks.filter((w) => w.ok).length}/${Math.ceil(c.durationDays / 7)}`}</b><div className="text-muted">{c.type === "boss" ? "المجموع" : c.type === "daily" ? "أيام ناجحة" : "أسابيع ناجحة"}</div></div><div className="rounded-xl bg-surface-2 p-2"><b>{st.todayValue}/{c.target}</b><div className="text-muted">اليوم</div></div><div className="rounded-xl bg-surface-2 p-2"><b className="text-gold">+{c.dailyReward}/يوم · +{c.successReward}</b><div className="text-muted">−{c.failurePenalty} فشل</div></div></div>
      {c.type === "daily" && <div className="mt-2 flex gap-0.5">{Object.entries(st.daily).map(([d, v]) => <span key={d} title={`${d}: ${v}`} className={cx("h-2 flex-1 rounded-full", v >= c.target ? "bg-ok" : d === todayISO() ? "bg-surface-2" : "bg-danger/60")} />)}</div>}
      {c.status === "active" && c.source === "manual" && <div className="mt-3 flex items-center gap-2"><NumberInput value={manual[c.id] ?? (c.progress[todayISO()] ?? 0)} onChange={(v) => setManual({ ...manual, [c.id]: v })} className="flex-1" /><Button size="sm" variant="primary" onClick={() => challengeActions.logProgress(c.id, todayISO(), manual[c.id] ?? (c.progress[todayISO()] ?? 0))}>تسجيل اليوم</Button></div>}
      <div className="mt-3 flex gap-1">{c.status !== "active" && <Button size="sm" onClick={() => challengeActions.restart(c.id)}>إعادة البدء</Button>}<Button size="sm" variant="ghost" onClick={() => confirm("حذف التحدي؟", () => challengeActions.remove(c.id))}>🗑 حذف</Button></div></Card>; })}</div>
    <Modal open={open} onClose={() => setOpen(false)} title="تحدٍ جديد" size="lg" footer={<Button variant="primary" disabled={!f.title.trim()} onClick={() => { challengeActions.add({ ...f, title: f.title.trim() }); setOpen(false); }}>ابدأ التحدي</Button>}>
      <div className="space-y-3"><Field label="العنوان"><Input autoFocus value={f.title} onChange={(e) => setF({ ...f, title: e.target.value })} placeholder="مثال: 30 يوم بلا سهر" /></Field>
        <div className="grid gap-2 sm:grid-cols-3">{TYPES.map((t) => <button key={t.id} type="button" onClick={() => setF({ ...f, type: t.id })} className={cx("touch rounded-2xl border p-3 text-start", f.type === t.id && "border-accent bg-accent-soft")}><div className="text-sm font-bold">{t.icon} {t.label}</div><div className="text-[11px] text-muted">{t.desc}</div></button>)}</div>
        <Grid><Field label="المصدر"><Select value={f.source} onChange={(e) => { const m = METRICS.find((x) => x.id === e.target.value); setF({ ...f, source: e.target.value, area: m?.area ?? f.area }); }}><option value="manual">يدوي (أسجل بنفسي)</option><optgroup label="مقاييس تلقائية">{METRICS.map((m) => <option key={m.id} value={m.id}>{m.label} ({m.unit})</option>)}</optgroup>{data.courses.length > 0 && <optgroup label="دورات (دروس مكتملة)">{data.courses.map((c) => <option key={c.id} value={`course:${c.id}`}>{c.title}</option>)}</optgroup>}</Select></Field><Field label={f.type === "boss" ? "الهدف الإجمالي" : f.type === "weekly" ? "الهدف الأسبوعي" : "الهدف اليومي"}><Input type="number" inputMode="decimal" value={f.target} onChange={(e) => setF({ ...f, target: Number(e.target.value) })} /></Field><Field label="المدة (أيام)"><Input type="number" value={f.durationDays} onChange={(e) => setF({ ...f, durationDays: Number(e.target.value) })} /></Field><Field label="تاريخ البدء"><Input type="date" value={f.startDate} onChange={(e) => setF({ ...f, startDate: e.target.value })} /></Field><Field label="مكافأة يومية XP"><Input type="number" value={f.dailyReward} onChange={(e) => setF({ ...f, dailyReward: Number(e.target.value) })} /></Field><Field label="مكافأة النصر XP"><Input type="number" value={f.successReward} onChange={(e) => setF({ ...f, successReward: Number(e.target.value) })} /></Field><Field label="عقوبة الفشل XP"><Input type="number" value={f.failurePenalty} onChange={(e) => setF({ ...f, failurePenalty: Number(e.target.value) })} /></Field></Grid>
        <Field label="المحور"><div className="flex flex-wrap gap-1.5">{AREAS.map((a) => <Chip key={a.id} active={f.area === a.id} color={a.color} onClick={() => setF({ ...f, area: a.id })}>{a.emoji} {a.label}</Chip>)}</div></Field></div>
    </Modal>{dialog}
  </div>);
}
export type { Challenge };
