"use client";
import React, { useState } from "react";
import { useApp } from "@/stores/app-store";
import { dumpActions } from "@/stores/actions";
import { AREAS, DumpKind } from "@/types/app-data";
import { todayISO } from "@/core/date";
import { Button, Card, Chip, EmptyState, Grid, NumberInput, StatCard, Tabs, Textarea, cx, useConfirm, AreaChip } from "@/components/ui";

const KINDS: { id: DumpKind; label: string; icon: string }[] = [{ id: "uncategorized", label: "غير مصنف", icon: "🌀" }, { id: "idea", label: "فكرة", icon: "💡" }, { id: "problem", label: "مشكلة", icon: "🧩" }, { id: "task", label: "مهمة", icon: "🗡️" }];
export default function BrainDumpPage() {
  const data = useApp((s) => s.data); const [text, setText] = useState(""); const [filter, setFilter] = useState<"inbox" | DumpKind | "processed">("inbox"); const [mins, setMins] = useState<Record<string, number>>({}); const { confirm, dialog } = useConfirm();
  const list = data.brainDumps.filter((d) => filter === "inbox" ? !d.processed && d.kind === "uncategorized" : filter === "processed" ? d.processed : d.kind === filter && !d.processed);
  return (<div className="space-y-4 anim-fade-up">
    <Card title="🧠 تفريغ العقل" subtitle="اكتب أي شيء. لا ترتيب. الفرز لاحقًا. +2 XP لكل تفريغ"><Textarea autoFocus className="min-h-[120px]" value={text} onChange={(e) => setText(e.target.value)} placeholder="ما الذي يشغل رأسك الآن؟" onKeyDown={(e) => { if (e.key === "Enter" && (e.metaKey || e.ctrlKey) && text.trim()) { dumpActions.add(text.trim()); setText(""); } }} /><div className="mt-2 flex items-center justify-between"><span className="text-[11px] text-muted">Ctrl/⌘ + Enter للحفظ</span><Button variant="primary" disabled={!text.trim()} onClick={() => { dumpActions.add(text.trim()); setText(""); }}>تفريغ</Button></div></Card>
    <Grid cols={4}><StatCard label="صندوق الوارد" value={data.brainDumps.filter((d) => !d.processed && d.kind === "uncategorized").length} tone="accent" /><StatCard label="أفكار" value={data.brainDumps.filter((d) => d.kind === "idea" && !d.processed).length} /><StatCard label="مشاكل" value={data.brainDumps.filter((d) => d.kind === "problem" && !d.processed).length} /><StatCard label="مُعالج" value={data.brainDumps.filter((d) => d.processed).length} tone="ok" /></Grid>
    <Tabs value={filter} onChange={setFilter} tabs={[{ id: "inbox", label: "الوارد" }, ...KINDS.slice(1).map((k) => ({ id: k.id, label: `${k.icon} ${k.label}` })), { id: "processed", label: "✓ مُعالج" }]} />
    <div className="space-y-2">{list.length === 0 && <EmptyState icon="🍃" title="فارغ" description="رأس صافٍ." />}{list.map((d) => <Card key={d.id} className={cx("p-3", d.processed && "opacity-70")}><p className="whitespace-pre-wrap text-sm">{d.text}</p><div className="mt-2 flex flex-wrap items-center gap-1.5 text-[11px] text-muted"><span>{d.date}</span>{d.area && <AreaChip id={d.area} small />}{d.minutes ? <span>⏱ {d.minutes} د</span> : null}{d.convertedTo && <span className="rounded bg-ok/15 px-1.5 text-ok">حُوّل: {d.convertedTo.split(":")[0]}</span>}</div>
      {!d.processed && <div className="mt-2 space-y-2"><div className="flex flex-wrap gap-1">{KINDS.map((k) => <Chip key={k.id} active={d.kind === k.id} onClick={() => dumpActions.triage(d.id, k.id, d.area)}>{k.icon} {k.label}</Chip>)}</div><div className="flex flex-wrap gap-1">{AREAS.map((a) => <Chip key={a.id} active={d.area === a.id} color={a.color} onClick={() => dumpActions.triage(d.id, d.kind, a.id)}>{a.emoji}</Chip>)}</div><div className="flex flex-wrap items-center gap-2"><Button size="sm" onClick={() => dumpActions.convertToTask(d, todayISO())}>→ مهمة اليوم</Button><Button size="sm" onClick={() => dumpActions.convertToIdea(d)}>→ بنك الأفكار</Button><div className="flex items-center gap-1"><NumberInput value={mins[d.id] ?? 15} step={5} suffix="د" onChange={(v) => setMins({ ...mins, [d.id]: v })} className="w-32" /><Button size="sm" onClick={() => dumpActions.logMinutes(d.id, mins[d.id] ?? 15)}>تسجيل وقت</Button></div><Button size="sm" variant="ghost" onClick={() => dumpActions.markProcessed(d.id)}>✓ تمت معالجته</Button><Button size="sm" variant="ghost" onClick={() => confirm("حذف؟", () => dumpActions.remove(d.id))}>🗑</Button></div></div>}
      {d.processed && <Button size="sm" variant="ghost" className="mt-1" onClick={() => dumpActions.markProcessed(d.id, false)}>إرجاع</Button>}</Card>)}</div>{dialog}
  </div>);
}
